### ISSUE TITLE
Some doubts in v1.2/ispConfig.example.py

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#103]
# How many Mbps are available to the edge of this network
upstreamBandwidthCapacityDownloadMbps = 1000
upstreamBandwidthCapacityUploadMbps = 1000

What does it means ? What value would we place here ? Card rate or Total Banwidth we have ?

Assume the card is 2 Port x 10 Gigabits and bandwith is also 10 Gigabits (although not consistent) what should be the value ?

Or 

If there is 2 card 2 Port x 10 Gigabit and 20 Gigabit (same not consistent) what should be the value ?

**Comment by rchac** [comment]
> Total Banwidth we have ?

Yes, it refers to the bandwidth your network has available upstream to the global internet.

**Comment by interduo** [comment]
I see in tc manual so interesting thing:
```
       ceil rate
              Maximum rate at which a class can send, if its parent has
              bandwidth to spare.  Defaults to the configured rate,
              which implies no borrowing
```

If ceil is optional could we just set the rates in `linux_tc.txt` when there is a flat design?

**Comment by marsalans** [comment]
> > Total Banwidth we have ?
> 
> Yes, it refers to the bandwidth your network has available upstream to the global internet.

Alright.
