### ISSUE TITLE
Some doubts about receiving entries in ShapedDevices.example.csv

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#104]
Since we do not fill this file manually, how will this help ?

# Traffic from devices not specified in Shaper.csv will be rate limited by an HTB of this many Mbps
defaultClassCapacityDownloadMbps = 500
defaultClassCapacityUploadMbps = 500

And what would be the impact if the queue automatically created on mikrotik by radius by default will be removed by api, and until the time sync is completing will mikrotik starve itself ?

Or I did not make queue on mikrotik and just let it flow the traffic until the sync is completed ?

**Comment by rchac** [comment]
defaultClassCapacity is kind of pointless to include and poses risk of user error so it is now removed. It used to make sense before XDP was introduced but is sort of deprecated now. Removed with https://github.com/rchac/LibreQoS/commit/2161e3e4d8fe1966984540387242beff04065129 and https://github.com/rchac/LibreQoS/commit/b5d52dd31bebfdc5fc927708420190b74b3a46d6
