### ISSUE TITLE
How to recreate htb rules from accel-ppp ?

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#106]
Hi, i want to know about accel-ppp. If we used libreqos and accel-ppp on same machine what are the consequences ?

Like accel-ppp also create htb queues so after running accel-ppp then libreqos, will libreqos remove entries made by accel-ppp ?

Or we have to remove queue from accel-ppp ?

Or is there a way to use both at same time, like accel-ppp invoke libreqos code to make htb queues ?

Is there a benefit running both on same machine ?

Will there be benefit or downside of it ?

We have a lots of Mikrotik and we want to try accel-ppp for pppoe authentication. 

Is there a benfit of using accel-ppp or Mikrotik and if so, is there a benefit of using accel-ppp directly or via vyos ?

For now i have run libreqos seperately on a dedicated hardware and its easy via Mikrotik API to use Libreqos API or write directly to the csv file.

As mikrotik provide API so we can easily get queue data and pass to libreqos without hitting the radius.

What are the recommendation ?

**Comment by rchac** [comment]
I would run LibreQoS on a dedicated machine or at least a VM. It will likely cause unanticipated issues to run both on the same machine.

**Comment by marsalans** [comment]
what about other points ?

**Comment by rchac** [comment]
> Like accel-ppp also create htb queues so after running accel-ppp then libreqos, will libreqos remove entries made by accel-ppp ?

I would completely avoid running them on the same machine, unless as VMs with different interfaces.

>Or we have to remove queue from accel-ppp ?

That might be better

> Or is there a way to use both at same time, like accel-ppp invoke libreqos code to make htb queues ?

Possibly, but you'd need to write an integration to do that, and run them on separate machines / VMs / interfaces.

> Is there a benefit running both on same machine ?
> Will there be benefit or downside of it ?

Probably not the ideal way to do it.

> We have a lots of Mikrotik and we want to try accel-ppp for pppoe authentication.

> Is there a benfit of using accel-ppp or Mikrotik and if so, is there a benefit of using accel-ppp directly or via vyos ?

I am not familiar with accel-ppp so i cannot say.

> For now i have run libreqos seperately on a dedicated hardware and its easy via Mikrotik API to use Libreqos API or write directly to the csv file.
> As mikrotik provide API so we can easily get queue data and pass to libreqos without hitting the radius.

Great. This seems ideal!
