### ISSUE TITLE
v1.1?  IPv6?

### ISSUE THREAD

**Issue by syadnom** [rchac/LibreQoS#11]
rchac, I see your request over on the XDP page you've linked on getting IPv6 support there.  Wondering if you had any luck?   I'd consider pitching in a bit to make that happen.   I'm running preseem now, which I'm happy enough with but I wouldn't mind spending that money elsewhere and I also like that you've got site/AP/sub shaping in place today and I could REALLY put that to work.

**Comment by rchac** [comment]
I appreciate your feedback. I think you're right, I need to engage folks there again. I am still happy to put up the cash reward thing to make it happen. I am hoping with the more flexible hierarchy for HTBs in v1.1, the TCP latency tracking, and (soon?) IPv6 support - that LibreQoS can be a better fit for your ISP environment. I'm already running v1.1 in production and it's pretty nifty.

**Comment by syadnom** [comment]
ipv6 is basically a requirement for me.  I'm not ready to commit (because I'm still on preseem and haven't made a hard decision to leave them) but if v1.1 could have ipv6 and the stats screen you showed in the other thread, I'd pony up a bit of cash.

**Comment by lakelinx** [comment]
@rchac Id be happy to up your bounty another 1k if that helps to get it implemented.

**Comment by rchac** [comment]
Idea: I can adapt v1.2-alpha to have an XDP_multicore on/off toggle boolean. If False, it could use a regular one-CPU-core HTB structure with parent nodes within that, allowing IPv6 to work with regular hashed TC filters. It should handle somewhere between [4-6Gbps](https://yhbt.net/lore/all/20201211152649.12123-2-maximmi@mellanox.com/T/). Would this be helpful to those who need IPv6?

**Comment by syadnom** [comment]
> Idea: I can adapt v1.2-alpha to have an XDP_multicore on/off toggle boolean. If False, it could use a regular one-CPU-core HTB structure with parent nodes within that, allowing IPv6 to work with regular hashed TC filters. It should handle somewhere between 4-6Gbps. Would this be helpful to those who need IPv6?

This would be interesting.  Also would allow 'scale out' with cheaper
boxes, ie fast dual and quad cores vs trying to shove tons of fast
cores in one box.

**Comment by rchac** [comment]
Ok great. I'll start experimenting with it.

**Comment by rchac** [comment]
@syadnom Made progress with allowing XDP toggle / adding IPv6. We just need to test to confirm that there are no issues on execution. https://github.com/rchac/LibreQoS/pull/76

**Comment by rchac** [comment]
@syadnom Added IPv6 support for v1.2 (xdp off) and IPv6 support for UISP integration via MikroTik MAC association. Probably has some small bugs I haven't discovered so testing is welcome. https://github.com/rchac/LibreQoS/tree/main/v1.2

**Comment by rchac** [comment]
See https://github.com/rchac/LibreQoS/issues/98
