### ISSUE TITLE
Getting some errors after v1.1 recompilation

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#111]
I did a fresh installation of Ubuntu 22.04.1 and recompile v1.1, i know that there are changes in v1.1 when i successfully compiled it first time months ago.

![9ewrjaiddsdsasa](https://user-images.githubusercontent.com/36761603/191271679-1cac52fb-7b6d-4e49-98ba-5748f41a9bf0.PNG)

This is printed when i run `python3 ./LibreQoS.py`

I got some errors that class does not exist and Error loading BTF, libbpf: Error loading ELF section

`sudo tc filter delete dev enp4s0f0
Error: Class doesn't support blocks.
We have an error talking to the kernel
sudo tc filter delete dev enp4s0f0 root
Error: Specified class doesn't exist.
We have an error talking to the kernel
sudo tc qdisc delete dev enp4s0f0 root
sudo tc qdisc delete dev enp4s0f0
Error: Failed to find qdisc with specified handle.
sudo tc filter delete dev enp4s0f1
Error: Class doesn't support blocks.
We have an error talking to the kernel
sudo tc filter delete dev enp4s0f1 root
Error: Specified class doesn't exist.
We have an error talking to the kernel
sudo tc qdisc delete dev enp4s0f1 root
sudo tc qdisc delete dev enp4s0f1
Error: Failed to find qdisc with specified handle.
NIC queues:   12
CPU cores:    12
sudo ./xdp-cpumap-tc/bin/xps_setup.sh -d enp4s0f0 --default --disable
sudo ./xdp-cpumap-tc/bin/xps_setup.sh -d enp4s0f1 --default --disable
sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu --dev enp4s0f0 --lan
libbpf: Error loading BTF: Invalid argument(22)
libbpf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 504
str_off: 504
str_len: 1733
btf_total_size: 2261
[1] PTR (anon) type_id=2
[2] STRUCT xdp_md size=24 vlen=6
  data type_id=3 bits_offset=0
  data_end type_id=3 bits_offset=32
  data_meta type_id=3 bits_offset=64
  ingress_ifindex type_id=3 bits_offset=96
  rx_queue_index type_id=3 bits_offset=128
  egress_ifindex type_id=3 bits_offset=160
[3] TYPEDEF __u32 type_id=4
[4] INT unsigned int size=4 bits_offset=0 nr_bits=32 encoding=(none)
[5] FUNC_PROTO (anon) return=6 args=(1 ctx)
[6] INT int size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[7] FUNC xdp_program type_id=5
[8] STRUCT bpf_map_def size=24 vlen=6
  type type_id=4 bits_offset=0
  key_size type_id=4 bits_offset=32
  value_size type_id=4 bits_offset=64
  max_entries type_id=4 bits_offset=96
  map_flags type_id=4 bits_offset=128
  inner_map_idx type_id=4 bits_offset=160
[9] VAR map_ip_hash type_id=8 linkage=1
[10] VAR map_txq_config type_id=8 linkage=1
[11] VAR map_ifindex_type type_id=8 linkage=1
[12] VAR cpu_map type_id=8 linkage=1
[13] VAR cpus_available type_id=8 linkage=1
[14] INT char size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[15] ARRAY (anon) type_id=14 index_type_id=16 nr_elems=4
[16] INT __ARRAY_SIZE_TYPE__ size=4 bits_offset=0 nr_bits=32 encoding=(none)
[17] VAR _license type_id=15 linkage=1
[18] DATASEC license size=0 vlen=1 size == 0

libbpf: Error loading ELF section .BTF: -22. Ignored and continue.
TC workaround for mapname: map_ifindex_type map_fd:7

Added CPU:0 queue_size:2048

Added CPU:1 queue_size:2048

Added CPU:2 queue_size:2048

Added CPU:3 queue_size:2048

Added CPU:4 queue_size:2048

Added CPU:5 queue_size:2048

Added CPU:6 queue_size:2048

Added CPU:7 queue_size:2048

Added CPU:8 queue_size:2048

Added CPU:9 queue_size:2048

Added CPU:10 queue_size:2048

Added CPU:11 queue_size:2048

Documentation:

 XDP: Lookup IPv4 and redirect to CPU hash

This program loads the XDP eBPF program into the kernel.

Use the cmdline tool for add/removing dest IPs to the hash

 - Attached to device:enp4s0f0 (ifindex:9) prog_id:95

sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu --dev enp4s0f1 --wan
libbpf: Error loading BTF: Invalid argument(22)
libbpf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 504
str_off: 504
str_len: 1733
btf_total_size: 2261
[1] PTR (anon) type_id=2
[2] STRUCT xdp_md size=24 vlen=6
  data type_id=3 bits_offset=0
  data_end type_id=3 bits_offset=32
  data_meta type_id=3 bits_offset=64
  ingress_ifindex type_id=3 bits_offset=96
  rx_queue_index type_id=3 bits_offset=128
  egress_ifindex type_id=3 bits_offset=160
[3] TYPEDEF __u32 type_id=4
[4] INT unsigned int size=4 bits_offset=0 nr_bits=32 encoding=(none)
[5] FUNC_PROTO (anon) return=6 args=(1 ctx)
[6] INT int size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[7] FUNC xdp_program type_id=5
[8] STRUCT bpf_map_def size=24 vlen=6
  type type_id=4 bits_offset=0
  key_size type_id=4 bits_offset=32
  value_size type_id=4 bits_offset=64
  max_entries type_id=4 bits_offset=96
  map_flags type_id=4 bits_offset=128
  inner_map_idx type_id=4 bits_offset=160
[9] VAR map_ip_hash type_id=8 linkage=1
[10] VAR map_txq_config type_id=8 linkage=1
[11] VAR map_ifindex_type type_id=8 linkage=1
[12] VAR cpu_map type_id=8 linkage=1
[13] VAR cpus_available type_id=8 linkage=1
[14] INT char size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[15] ARRAY (anon) type_id=14 index_type_id=16 nr_elems=4
[16] INT __ARRAY_SIZE_TYPE__ size=4 bits_offset=0 nr_bits=32 encoding=(none)
[17] VAR _license type_id=15 linkage=1
[18] DATASEC license size=0 vlen=1 size == 0

libbpf: Error loading ELF section .BTF: -22. Ignored and continue.
TC workaround for mapname: map_ifindex_type map_fd:7

Added CPU:0 queue_size:2048

Added CPU:1 queue_size:2048

Added CPU:2 queue_size:2048

Added CPU:3 queue_size:2048

Added CPU:4 queue_size:2048

Added CPU:5 queue_size:2048

Added CPU:6 queue_size:2048

Added CPU:7 queue_size:2048

Added CPU:8 queue_size:2048

Added CPU:9 queue_size:2048

Added CPU:10 queue_size:2048

Added CPU:11 queue_size:2048

Documentation:

 XDP: Lookup IPv4 and redirect to CPU hash

This program loads the XDP eBPF program into the kernel.

Use the cmdline tool for add/removing dest IPs to the hash

 - Attached to device:enp4s0f1 (ifindex:10) prog_id:98

sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --clear
iphash_modify() IP:100.64.0.8 key:0x8004064 TC-handle:0x0
iphash_modify() IP:100.64.0.2 key:0x2004064 TC-handle:0x0
iphash_modify() IP:100.64.0.6 key:0x6004064 TC-handle:0x0
iphash_modify() IP:100.64.0.7 key:0x7004064 TC-handle:0x0
iphash_modify() IP:100.64.0.9 key:0x9004064 TC-handle:0x0
iphash_modify() IP:100.64.0.1 key:0x1004064 TC-handle:0x0
iphash_modify() IP:100.64.0.3 key:0x3004064 TC-handle:0x0
iphash_modify() IP:100.64.0.5 key:0x5004064 TC-handle:0x0
iphash_modify() IP:100.64.0.4 key:0x4004064 TC-handle:0x0
iphash_modify() IP:100.64.0.10 key:0xA004064 TC-handle:0x0
key: 0x8004064

key: 0x2004064

key: 0x6004064

key: 0x7004064

key: 0x9004064

key: 0x1004064

key: 0x3004064

key: 0x5004064

key: 0x4004064

key: 0xA004064

sudo ./xdp-cpumap-tc/src/tc_classify --dev-egress enp4s0f0
TC: Control program for tc_classify_kern.o

 - When using --dev, loads TC-egress filter calling BPF program

 - Config of map_txq_config, that control CPU to queue_mapping

 - List current queue_mapping (txq) config via --list

 Map filename: /sys/fs/bpf/tc/globals/map_txq_config

Dev:enp4s0f0 -- Loading: TC-clsact egress

 - Run: tc qdisc del dev enp4s0f0 clsact 2> /dev/null

 - Run: tc qdisc add dev enp4s0f0 clsact

 - Run: tc filter add dev enp4s0f0 egress prio 1 handle 1 bpf da obj ./xdp-cpumap-tc/src/tc_classify_kern.o sec tc_classify

sudo ./xdp-cpumap-tc/src/tc_classify --dev-egress enp4s0f1
TC: Control program for tc_classify_kern.o

 - When using --dev, loads TC-egress filter calling BPF program

 - Config of map_txq_config, that control CPU to queue_mapping

 - List current queue_mapping (txq) config via --list

 Map filename: /sys/fs/bpf/tc/globals/map_txq_config

Dev:enp4s0f1 -- Loading: TC-clsact egress

 - Run: tc qdisc del dev enp4s0f1 clsact 2> /dev/null

 - Run: tc qdisc add dev enp4s0f1 clsact

 - Run: tc filter add dev enp4s0f1 egress prio 1 handle 1 bpf da obj ./xdp-cpumap-tc/src/tc_classify_kern.o sec tc_classify

sudo tc qdisc replace dev enp4s0f0 root handle 7FFF: mq
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x1 handle 0x1: htb default 2
sudo tc class add dev enp4s0f0 parent 0x1: classid 0x1:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x1:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x1:1 classid 0x1:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x1:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x2 handle 0x2: htb default 2
sudo tc class add dev enp4s0f0 parent 0x2: classid 0x2:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x2:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x2:1 classid 0x2:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x2:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x3 handle 0x3: htb default 2
sudo tc class add dev enp4s0f0 parent 0x3: classid 0x3:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x3:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x3:1 classid 0x3:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x3:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x4 handle 0x4: htb default 2
sudo tc class add dev enp4s0f0 parent 0x4: classid 0x4:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x4:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x4:1 classid 0x4:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x4:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x5 handle 0x5: htb default 2
sudo tc class add dev enp4s0f0 parent 0x5: classid 0x5:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x5:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x5:1 classid 0x5:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x5:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x6 handle 0x6: htb default 2
sudo tc class add dev enp4s0f0 parent 0x6: classid 0x6:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x6:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x6:1 classid 0x6:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x6:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x7 handle 0x7: htb default 2
sudo tc class add dev enp4s0f0 parent 0x7: classid 0x7:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x7:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x7:1 classid 0x7:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x7:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x8 handle 0x8: htb default 2
sudo tc class add dev enp4s0f0 parent 0x8: classid 0x8:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x8:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x8:1 classid 0x8:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x8:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0x9 handle 0x9: htb default 2
sudo tc class add dev enp4s0f0 parent 0x9: classid 0x9:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0x9:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0x9:1 classid 0x9:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0x9:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0xa handle 0xa: htb default 2
sudo tc class add dev enp4s0f0 parent 0xa: classid 0xa:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0xa:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0xa:1 classid 0xa:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0xa:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0xb handle 0xb: htb default 2
sudo tc class add dev enp4s0f0 parent 0xb: classid 0xb:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0xb:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0xb:1 classid 0xb:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0xb:2 cake diffserv4
sudo tc qdisc add dev enp4s0f0 parent 7FFF:0xc handle 0xc: htb default 2
sudo tc class add dev enp4s0f0 parent 0xc: classid 0xc:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f0 parent 0xc:1 cake diffserv4
sudo tc class add dev enp4s0f0 parent 0xc:1 classid 0xc:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f0 parent 0xc:2 cake diffserv4
sudo tc qdisc replace dev enp4s0f1 root handle 7FFF: mq
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x1 handle 0x1: htb default 2
sudo tc class add dev enp4s0f1 parent 0x1: classid 0x1:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x1:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x1:1 classid 0x1:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x1:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x2 handle 0x2: htb default 2
sudo tc class add dev enp4s0f1 parent 0x2: classid 0x2:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x2:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x2:1 classid 0x2:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x2:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x3 handle 0x3: htb default 2
sudo tc class add dev enp4s0f1 parent 0x3: classid 0x3:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x3:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x3:1 classid 0x3:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x3:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x4 handle 0x4: htb default 2
sudo tc class add dev enp4s0f1 parent 0x4: classid 0x4:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x4:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x4:1 classid 0x4:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x4:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x5 handle 0x5: htb default 2
sudo tc class add dev enp4s0f1 parent 0x5: classid 0x5:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x5:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x5:1 classid 0x5:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x5:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x6 handle 0x6: htb default 2
sudo tc class add dev enp4s0f1 parent 0x6: classid 0x6:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x6:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x6:1 classid 0x6:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x6:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x7 handle 0x7: htb default 2
sudo tc class add dev enp4s0f1 parent 0x7: classid 0x7:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x7:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x7:1 classid 0x7:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x7:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x8 handle 0x8: htb default 2
sudo tc class add dev enp4s0f1 parent 0x8: classid 0x8:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x8:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x8:1 classid 0x8:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x8:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0x9 handle 0x9: htb default 2
sudo tc class add dev enp4s0f1 parent 0x9: classid 0x9:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0x9:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0x9:1 classid 0x9:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0x9:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0xa handle 0xa: htb default 2
sudo tc class add dev enp4s0f1 parent 0xa: classid 0xa:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0xa:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0xa:1 classid 0xa:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0xa:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0xb handle 0xb: htb default 2
sudo tc class add dev enp4s0f1 parent 0xb: classid 0xb:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0xb:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0xb:1 classid 0xb:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0xb:2 cake diffserv4
sudo tc qdisc add dev enp4s0f1 parent 7FFF:0xc handle 0xc: htb default 2
sudo tc class add dev enp4s0f1 parent 0xc: classid 0xc:1 htb rate 10000mbit ceil 10000mbit
sudo tc qdisc add dev enp4s0f1 parent 0xc:1 cake diffserv4
sudo tc class add dev enp4s0f1 parent 0xc:1 classid 0xc:2 htb rate 2.5mbit ceil 10mbit prio 5
sudo tc qdisc add dev enp4s0f1 parent 0xc:2 cake diffserv4

Site_1
Download:  1900 to 2000 Mbps
Upload:    1900 to 2000 Mbps
sudo tc class add dev enp4s0f0 parent 1:1 classid 0x3 htb rate 1900mbit ceil 2000mbit prio 3
sudo tc class add dev enp4s0f1 parent 1:1 classid 0x3 htb rate 1900mbit ceil 2000mbit prio 3

   Device 1
   Download:  27 to 169 Mbps
   Upload:    5 to 22 Mbps
   sudo tc class add dev enp4s0f0 parent 0x1:0x3 classid 0x4 htb rate 27mbit ceil 169mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x1:0x4 cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x1:0x3 classid 0x4 htb rate 5mbit ceil 22mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x1:0x4 cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.1 --cpu 0x0 --classid 0x1:0x4
key: 0x1004064

iphash_modify() IP:100.64.0.1 key:0x1004064 TC-handle:0x10004

   Device 2
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x1:0x3 classid 0x5 htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x1:0x5 cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x1:0x3 classid 0x5 htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x1:0x5 cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.2 --cpu 0x0 --classid 0x1:0x5
key: 0x2004064

iphash_modify() IP:100.64.0.2 key:0x2004064 TC-handle:0x10005

Site_2
Download:  1900 to 2000 Mbps
Upload:    1900 to 2000 Mbps
sudo tc class add dev enp4s0f0 parent 1:1 classid 0x6 htb rate 1900mbit ceil 2000mbit prio 3
sudo tc class add dev enp4s0f1 parent 1:1 classid 0x6 htb rate 1900mbit ceil 2000mbit prio 3

   Device 3
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x2:0x6 classid 0x7 htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x2:0x7 cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x2:0x6 classid 0x7 htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x2:0x7 cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.3 --cpu 0x1 --classid 0x2:0x7
key: 0x3004064

iphash_modify() IP:100.64.0.3 key:0x3004064 TC-handle:0x20007

   Device 4
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x2:0x6 classid 0x8 htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x2:0x8 cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x2:0x6 classid 0x8 htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x2:0x8 cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.4 --cpu 0x1 --classid 0x2:0x8
key: 0x4004064

iphash_modify() IP:100.64.0.4 key:0x4004064 TC-handle:0x20008

Site_3
Download:  1900 to 2000 Mbps
Upload:    1900 to 2000 Mbps
sudo tc class add dev enp4s0f0 parent 1:1 classid 0x9 htb rate 1900mbit ceil 2000mbit prio 3
sudo tc class add dev enp4s0f1 parent 1:1 classid 0x9 htb rate 1900mbit ceil 2000mbit prio 3

   Device 5
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x3:0x9 classid 0xa htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x3:0xa cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x3:0x9 classid 0xa htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x3:0xa cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.5 --cpu 0x2 --classid 0x3:0xa
key: 0x5004064

iphash_modify() IP:100.64.0.5 key:0x5004064 TC-handle:0x3000A

   Device 6
   Download:  27 to 98 Mbps
   Upload:    5 to 16 Mbps
   sudo tc class add dev enp4s0f0 parent 0x3:0x9 classid 0xb htb rate 27mbit ceil 98mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x3:0xb cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x3:0x9 classid 0xb htb rate 5mbit ceil 16mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x3:0xb cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.6 --cpu 0x2 --classid 0x3:0xb
key: 0x6004064

iphash_modify() IP:100.64.0.6 key:0x6004064 TC-handle:0x3000B

Site_4
Download:  1900 to 2000 Mbps
Upload:    1900 to 2000 Mbps
sudo tc class add dev enp4s0f0 parent 1:1 classid 0xc htb rate 1900mbit ceil 2000mbit prio 3
sudo tc class add dev enp4s0f1 parent 1:1 classid 0xc htb rate 1900mbit ceil 2000mbit prio 3

   Device 7
   Download:  27 to 169 Mbps
   Upload:    5 to 22 Mbps
   sudo tc class add dev enp4s0f0 parent 0x4:0xc classid 0xd htb rate 27mbit ceil 169mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x4:0xd cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x4:0xc classid 0xd htb rate 5mbit ceil 22mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x4:0xd cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.7 --cpu 0x3 --classid 0x4:0xd
key: 0x7004064

iphash_modify() IP:100.64.0.7 key:0x7004064 TC-handle:0x4000D

   Device 8
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x4:0xc classid 0xe htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x4:0xe cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x4:0xc classid 0xe htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x4:0xe cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.8 --cpu 0x3 --classid 0x4:0xe
key: 0x8004064

iphash_modify() IP:100.64.0.8 key:0x8004064 TC-handle:0x4000E

Site_5
Download:  1900 to 2000 Mbps
Upload:    1900 to 2000 Mbps
sudo tc class add dev enp4s0f0 parent 1:1 classid 0xf htb rate 1900mbit ceil 2000mbit prio 3
sudo tc class add dev enp4s0f1 parent 1:1 classid 0xf htb rate 1900mbit ceil 2000mbit prio 3

   Device 9
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x5:0xf classid 0x10 htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x5:0x10 cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x5:0xf classid 0x10 htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x5:0x10 cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.9 --cpu 0x4 --classid 0x5:0x10
key: 0x9004064

iphash_modify() IP:100.64.0.9 key:0x9004064 TC-handle:0x50010

   Device 10
   Download:  27 to 114 Mbps
   Upload:    5 to 20 Mbps
   sudo tc class add dev enp4s0f0 parent 0x5:0xf classid 0x11 htb rate 27mbit ceil 114mbit prio 3
   sudo tc qdisc add dev enp4s0f0 parent 0x5:0x11 cake diffserv4
   sudo tc class add dev enp4s0f1 parent 0x5:0xf classid 0x11 htb rate 5mbit ceil 20mbit prio 3
   sudo tc qdisc add dev enp4s0f1 parent 0x5:0x11 cake diffserv4
   sudo ./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 100.64.0.10 --cpu 0x4 --classid 0x5:0x11
key: 0xA004064

iphash_modify() IP:100.64.0.10 key:0xA004064 TC-handle:0x50011

Successful run completed on 20/09/2022 13:42:27
Program complete
`

**Comment by interduo** [comment]
@marsalans this is dullicate of: https://github.com/rchac/LibreQoS/issues/63 right?

**Comment by marsalans** [comment]
I think that its similar.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by interduo** [comment]
Its a good way to make issue as short as possible and attach debug output as github gist link.

**Comment by marsalans** [comment]
That's a good news ☺️

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
