### ISSUE TITLE
Packet drop counter

### ISSUE THREAD

**Issue by dtaht** [rchac/LibreQoS#114]
It feels really good to me to learn of so many packets being dropped and marked for the good of the internet. Back in the old days, web pages used to have a counter for hits on them, and McDonalds would have "billions and billions" of burgers served. One of my fights has always been that "packet drops are *good*" - see for example, this podcast: https://www.modem.show/post/s01e07/

And I fought against the consumer labeling attempt to actually have packet drop (because it is largely an uncountable quantity) on it, but making the point, very visibly, that packet drop is good, would be good. 

So being able to put up on a webpage somewhere "Proudly dropping X,XXX,XXX,XXX packets since INSTALLATION_DATE", would be sort of pleasing. I have been trying to figure out the energy cost vs a vs dropping vs marking, also, over here: https://www.linkedin.com/feed/update/urn:li:activity:6977711685415444480/ 

Ironically we most see the most benefit for many applications from the fq_part but I'm unsure how to estimate that.

**Comment by rchac** [comment]
Ok great. Makes sense to add. Should we also be graphing packet drops? I was considering adding that. Not sure whether packet drops should be measured by quantity within that interval of time, or as a percentage of packets moved within the interval of time. Any recommendation?

**Comment by dtaht** [comment]
What we did in some openwrt project somewhere for cake was drawing on an inverse log scale
marks,drops,ack-drops,packets

**Comment by rchac** [comment]
v1.2 now tracks total packets dropped from all time in the file longTermStats.json
```
{"droppedPacketsTotal": 11338847.0}
```

It also now graphs packet drops as a % of total packets sent, by node (to help gauge degree of over-subscription).
![image](https://user-images.githubusercontent.com/22501920/192137243-f1ab208b-1602-4c11-a290-220c09118102.png)

**Comment by dtaht** [comment]
Cool! I know it's considerably more difficult, but breaking out drops by access catagory (tins), and excluding ack-drops (which are non-congestive in nature), and marks! oh my! :) Also, freezing the codebase for a real 1.2 release by next week would be sane...

**Comment by rchac** [comment]
Some progress ![image](https://user-images.githubusercontent.com/22501920/192157122-4dba7120-4d4e-4547-829c-860d52dd986f.png)

**Comment by dtaht** [comment]
Cooler still. Not sure if I understand your intent, though. In this plot you are trying to see the percentage drops vs each tin?


|best effort| voice | video| bulk|
|drops/packets|drops/packets|drops/packets|drops/packets|

**Comment by rchac** [comment]
Improved 
![image](https://user-images.githubusercontent.com/22501920/192198475-64ec4418-4eab-4f4c-b68b-f2b7d383e089.png)
Using (marks + drops - ackdrops) / packets

**Comment by dtaht** [comment]
inverse log2 would show more detail. Also, wow 4-6% congestive packet drop is a LOT

**Comment by dtaht** [comment]
btw, it turned out I DID get my math wrong. $50/100m packets.

**Comment by rchac** [comment]
I don't think it's possible yet with InfluxDB, though i'd like to use inverse log2 instead. https://github.com/influxdata/influxdb/issues/20551

And here are some more normalized stats over the course of an hour mid-day.

![image](https://user-images.githubusercontent.com/22501920/192358620-960a4220-8938-421b-bd1a-b57d5012893b.png)

**Comment by dtaht** [comment]
pretty. What do you mean by download by tin? % of total capacity? I don't understand the purple vs blue graph on the bottom left third. Would dots be better than lines?

Another line - a totals line (black) obviously that would have to be white on this background.

**Comment by rchac** [comment]
Download by tin and upload by tin just graph the % of total network traffic being categorized into each diffserv tin. Usually best effort is 90+% but it's neat to watch the percentage change throughout the day as users log into video conference calls and such.

**Comment by dtaht** [comment]
I am not aware of any videoconferencing apps that actively attempt to use dscp marks by default. It's usually an admin only setting. But it would be great if some were trying, and even better, if it was actually doing good.

**Comment by syadnom** [comment]
Most VoIP softphones mark DSCP packets by default.  Zoom/teams etc however don't.  Also note that many ISPs and wISPs will strip DSCP because customers can cheat.  Ie, tag their torrent downloads to expedited to gain priority.

**Comment by dtaht** [comment]
The reason why cake does soft admission control for dscp generally means that attempts to mis-use it are not rewarded. Say, for example, someone put their torrent into EF, well, they get at most 6.5% of the bandwidth... torrent clients by default also are generally bandwidth limited, you have to take explicit action to override that. It was my hope, actually, that torrent clients would mark themselves "LE" by default. 

Now along your backhaul, some thought is requred, here is where the per host fq in cake helps more than respecting dscp to a huge extent.

**Comment by syadnom** [comment]
problem is that some radios (ubiquiti) do DSCP/TOS prioritization automatically and it cannot be disabled.  Not only that, but they do it poorly.   Just like their capacity numbers are fantasy so we can't poll a radio for capacity and adapt a shaper accordingly without building in a huge padding (claims 250Mbps, can really do 120Mbps...) 

So we don't really know why one of these radios is dropping packets, via lost data or dropped due to priority. 

It would be unbelievable to have the shaping tree be able to poll a backhaul device and extract modulation and update the shaper in more-or-less real time... maybe someday.

**Comment by dtaht** [comment]
The very first use of fq_codel was on a pair of nanostation M5s on a p2p link, with dscps disabled. Cake also has a wash option which can be used selectively on radios that are not doing the right things with dscp.

**Comment by syadnom** [comment]
ubiquiti would likely never agree to any sort of compliance.  they likely wouldn't return email asking them to look at it these days.  Dramatically different company today than when then when the M5 series was king.

**Comment by dtaht** [comment]
UBNT Smart queues was done over a weekend by me for ubnt back in 2013, the userbase lept all over it and polished it up, and it's been a standard feature ever since. We've been maintaining a cake port to the udm series for 5+ years I know all the great people there in SJC left but there's always a chance they'll reform when faced with competition, at least. 

Often companies respond to market demand and threats. There's also: http://www-personal.umich.edu/~jlawler/aue/sig.html
Nastrudin only had a year, I've had 12. Neigh-boring on song, we are, I think.

**Comment by dtaht** [comment]
What was the final form of this? (marks and drops and backlogs, etc?)
