### ISSUE TITLE
Make use tc --batch for queues definitions

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#119]
I see improvement in this area:
https://github.com/rchac/LibreQoS/blob/main/v1.2/LibreQoS.py#L722-L769

The definitions for all root classes (deleting and creating should be loaded with `tc -f --batch`)

It would be very helpful also for: https://github.com/rchac/LibreQoS/issues/47
(now we get about 200 tc lines - loading one by one and every one using `shell()` is not so performant)

And main thing: If queues definition don't change this could also not be touched while reloading - is it possible?
(network.json and variables in ispConfig.py)

**Comment by dtaht** [comment]
tc -b - 
will load the rules from standard input. Piping is straightforward in both rust and python, but it pays to be cautious and load dependencies and check the error code(s).

**Comment by rchac** [comment]
You should see a slight improvement with https://github.com/rchac/LibreQoS/commit/ac75a0e44e5ec81526e939a064806aa346acf99b

**Comment by interduo** [comment]
How many cores do You use for Libre when counting 28%?

**Comment by rchac** [comment]
> How many cores do You use for Libre when counting optimalisation results?
> (more cores bigger result) 

12 cores

**Comment by interduo** [comment]
On my dev-libreqos (test instance) there is a change from:
time LibreQoS.py
```
real	0m23.901s
user	0m10.535s
sys	0m14.595s
```

to:
```
Executed 4007 XDP-CPUMAP-TC IP filter commands
iphash_modify() IP:172.16.252.32 key:0x20FC10AC TC-handle:0x80C69
iphash_modify() IP:172.19.18.17 key:0x111213AC TC-handle:0x80C6A
Queue and IP filter reload completed in 0.3 seconds
	TC commands: 	0.9 seconds
	XDP setup: 	 0.3 seconds
	XDP filters: 	 0.1 seconds
refreshShapers completed on 26/09/2022 09:53:19

real	0m14.896s
user	0m9.133s
sys	0m12.794s
```

Was that value `Queue and IP filter reload completed in 0.3 seconds` properly counted?
Value should be calculated as: 0.9+0.1+0.3 =1.3 and not 0.3? Am I right or this value meaning is slightly different?

**Comment by rchac** [comment]
> Value should be calculated as: 0.9+0.1+0.3 =1.3 and not 0.3? Am I right or this value meaning is slightly different?

You are right, thanks for catching that. Fixed with https://github.com/rchac/LibreQoS/commit/ad41a616bb8bcabe36755500b840ab80e6d07110

> in my prod there is a ~33% less reload time.

Awesome!
