### ISSUE TITLE
Backhaul level hierarchy?

### ISSUE THREAD

**Issue by syadnom** [rchac/LibreQoS#12]
I know there are other posts on this, but I didn't want to muddy them up.

Here's the challenge.  A long chain of backhauls with multiple sites in the chain and of coarse, multiple APs per site.

Edge->backhaul_Edge-to-1_2Gbps->site1>backhaul_1-to-2_1Gbps->site2->backhaul_x-to-y_zMbps...

The challenge is that the first backhaul really would like an HTB type shaper that encompasses all downstream sites in the 'normal' routing path.  Forget redundant paths here so not confusing topology to work around.  Site shapers is nice, that could be used to accommodate a known backhaul limit.  And 'undersizing' the site shaper could be used to reserve capacity for next hops manually.  You could see this getting out of hand really quickly though.

So Sites{1..n} should all get some equal cut of backhaul 'Edge-to-2'
next hope, sites{2..n} should get some equal cut of backhaul '1-to-2'
and so on.

How rough would it be stacking up HTBs like this?  I realize that this likely means that the top level HTB get's bound to a single CPU so would encourage getting the fastest cores possible to pull such a thing off, but I'm generally talking about wISP available backhauls here so ~2Gbps is up there in the top range.  Not many of us can make short range mmWave 10Gbps radios work in our long links.

I'm imagining a link path csv
edge facing on the left
from site, to site, dl-capacity, ul-capacity (potentially min capacity, max capacity like the client list as well). 
Then building this out documenting each link which could build either a stacked HTB (preferred) or just site shapers with those reserves for next hops calculated (somewhat functional)

**Comment by rchac** [comment]
If I am understanding correctly, the new Network.json hierarchical format introduced in v1.1-alpha may be exactly what you want. Any "Parent Node" (site, micro-pop, AP, whatever you want) can have child devices, as well as child nodes (site, micro-pop, AP, etc). https://github.com/rchac/LibreQoS/blob/main/v1.1/network.json

**Comment by rchac** [comment]
Basically each node or site would be able to use "up to" its bandwidth limits.
Is this reflective of the scenario you mean?
Core > Backhaul (2Gbps) > Site1 (2Gbps ceil) > Backhaul2 (500Mbps) > Site2 (500Mbps ceil)
If that is your layout, then site1 can use to up 2000Mbps if Site2 has low load. If Site1 has high load, Site2 still gets a fair allocation of bandwidth in proportion to the number of child devices (for example, maybe 1750 for site1, 250 for site2). What we might want to do is calculate the min rate for nodes based on the cumulative min bandwidth set for any child devices lower in its hierarchy. That way there's no risk of under-delivering bandwidth to nodes deeply nested many layers down.

**Comment by syadnom** [comment]
yeah, we're on the same page here.  basically, how to spread that backhaul out evenly.  

What we're trying to do is maximize peak plan speeds.  Moving from ~25Mbps plans  to 100Mbps plans puts more 'burst' pressure on backhauls.  We're not using any 'bursting', but we see devices like apple tv's that will fill their buffers really aggressively.  a 100Mbps plan with an apple tv 4k will pull 100Mbps every 20 seconds or whatever instead of a constant 5Mbps.

Currently using preseem and doing AP shaping which does help, but having 10 APs on a POP means that all 10 can end up hitting the backhaul at the same time and there's no shaper on that backhaul.  Then the next backhaul up the chain also has nothing and so on.

Having stacked shapers would allow more peak oversell ie faster plan speeds.  We already know that moving people from a 25 to a 50 or 100 barely moves the average use.

**Comment by rchac** [comment]
I get what you mean. That's exactly why I like using LibreQoS, it protects the back-hauls from getting overloaded and we can much more aggressively oversub sites when we need to. And sites further up the chain are protected from being overloaded too. It has made it much easier for us to safely provide 100-500Mbps via fixed wireless.
