### ISSUE TITLE
WIKIUPDATE: ShapedDevices.csv

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#124]
1. Please add "All minimum plan rates for Circuits are 2M"
2. "Recommendation: set the min bandwidth to something like 25/10 and max to 1.15X advertised plan rate."
Add "by using bandwidthOverheadFactor = 1.15"

**Comment by rchac** [comment]
[Fixed](https://github.com/rchac/LibreQoS/wiki/LibreQoS-v1.2-Installation-&-Usage-Guide-Physical-Server-and-Ubuntu-22.04/663987ca0794bec92474afacb6615c27fd71bedd)! Thanks for catching that.
