### ISSUE TITLE
combined AP/Backhaul in topology?

### ISSUE THREAD

**Issue by syadnom** [rchac/LibreQoS#128]
What would it look like if you have an AP that is also acting like a backhaul?

For example, ubiquiti's wave.  The model is a number of wave APs feeding out to both customers and to repeaters.  

Another is cambiums cnwave as an underlay network.  cnwave builds a high capacity tree (it's only mesh for backup paths effectively...) and then you hang some 5Ghz APs off a site fed by cnwave.  The cnwave network is both 'AP' and 'Backhaul'.

I'm kinda handling this in mikrotik right now and adding a virtual level in the shaper tree so the 'AP' *LOOKS* like it's connected to the backhaul from the shaper's perspective.

Thoughts?

**Comment by rchac** [comment]
You could certainly do that.
There is no strict AP/Backhaul concept in v1.1/v1.2, just nodes, so it gives the flexibility to do things exactly like this.
So for example if you have a WaveAP connected to Site_1, and the WaveAP feeds two PoPs:
```
{
	"Site_1":
		{
		"downloadBandwidthMbps":1000,
		"uploadBandwidthMbps":1000,
		"children":
			{
				"LTU-AP-1":
					{
					"downloadBandwidthMbps":500,
					"uploadBandwidthMbps":500
					},
				"WaveAP-1":
					{
					"downloadBandwidthMbps":500,
					"uploadBandwidthMbps":500,
					"children":
						{
							"PoP-1":
							{
							"downloadBandwidthMbps":200,
							"uploadBandwidthMbps":200,
							"children":
								{
									"LTU-AP-2":
									{
										"downloadBandwidthMbps":200,
										"uploadBandwidthMbps":200
									},
									"LTU-AP-3":
									{
										"downloadBandwidthMbps":200,
										"uploadBandwidthMbps":200
									}
								}
							},
							"PoP-2":
							{
							"downloadBandwidthMbps":200,
							"uploadBandwidthMbps":200,
							"children":
								{
									"LTU-AP-4":
									{
										"downloadBandwidthMbps":200,
										"uploadBandwidthMbps":200
									},
									"LTU-AP-5":
									{
										"downloadBandwidthMbps":200,
										"uploadBandwidthMbps":200
									}
								}
							}
						}
					}
			}
		}
}
```

**Comment by syadnom** [comment]
Does this tree lock all the downstream shapers on a single CPU core?

Also, the names in quotes here are the names that we'd pull out of CRM yes?  so customer175 connects to "LTU-AP-4" in UISP so we need "LTU-AP-4" in the config right?

**Comment by syadnom** [comment]
also, I notice that you didn't oversubscribr site1, LTU-AP-1 and WaveAP-1 both set to 500x500.  That's not an important detail right?  ie, WaveAP-1 could be at 2Gx500M and LTU-AP-1 at 300x50 yes?  Ideally, I'm setting each link at is potential so when I upgrade at the head end, it doesn't need re-engineered.

And I'm really muddying this post up here... but in your language here, 'Site' is basically 'headend' right, and 'PoP' is all the subordinate points-of-presence/towers/repeaters/etc?  ie, all of these 'sites' and 'pops' are going to line up to a "Site" in UISP.  Site-1 is a 'site' as is PoP-1 in UISP lingo.

**Comment by rchac** [comment]
In the above example, Site_1 and child sites are bound to a single CPU core. So 2.5 Gbps or more throughput on CAKE, and 4 Gbps or so with fq_codel. Or more if you can split up "Site_1" to multipl top level nodes. And that's exactly right, the names in quotes need to match the name of the AP or site the clients in UISP show being connected to.

**Comment by rchac** [comment]
> also, I notice that you didn't oversubscribr site1, LTU-AP-1 and WaveAP-1 both set to 500x500. That's not an important detail right? ie, WaveAP-1 could be at 2Gx500M and LTU-AP-1 at 300x50 yes? Ideally, I'm setting each link at is potential so when I upgrade at the head end, it doesn't need re-engineered.

Exactly right. You can set the AP to its true limits (2G x 500M) and LibreQoS knows to limit that if the parent node is less. So if the site above it was 500x250 for example that would limit the enforced speed of the AP to 500x250. It takes the MIN between the provided AP bandwidth rates and that of the parent site.

> And I'm really muddying this post up here... but in your language here, 'Site' is basically 'headend' right, and 'PoP' is all the subordinate points-of-presence/towers/repeaters/etc? ie, all of these 'sites' and 'pops' are going to line up to a "Site" in UISP. Site-1 is a 'site' as is PoP-1 in UISP lingo.

Yes, correct. In UISP terms PoPs and Sites are all just distinct sites with different hierarchy levels and parent sites. 👍
