### ISSUE TITLE
Installation break down

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#13]
1. Install and compile XDP-CPUMAP-TC
The v1.1 git submodule seems not to exist. https://github.com/rchac/LibreQoS/blob/main/.gitmodules
any work around?

**Comment by rchac** [comment]
Thank you for reporting. I went ahead and added the xdp-cpumap-tc submodule to v1.1. Could you please try again and see if it works now?

**Comment by mwangi-kiboi** [comment]
Good working
