### ISSUE TITLE
UISP Integration

### ISSUE THREAD

**Issue by thebracket** [rchac/LibreQoS#14]
Hi!

We chatted on Facebook about extending UISP Integration a bit. As promised, I threw together some code that works for our network. It's in Rust (since that's what I use 90% of the day, and my Python skills are really out-dated). 

You can find the code here: https://github.com/thebracket/libre_qos_rs/tree/main/uisp_integration

It's similar to the existing integration, and I've tried to retain compatibility with 1.1 alpha.

The first time you run it, it walks the entire UISP tree and builds your `network.json` topology - with everything defaulting to 1Gbps speed. It knows about "other" devices, so those of us who use that to manage devices from other vendors are supported. It also doesn't care about device models; we have a whole bunch of older Ubiquiti equipment, and didn't want to type in a giant list of radio models!

Once the first run is done, you have `network.json` in the format shown in the repo. `Shaper.csv` is populated with customers. Two additional files appear: `Sites.csv` lists all the sites it found, and `AccessPoints.csv` lists all the APs it found. You can edit the speed limits listed in these files, and on the *next* run - the correct values will be placed in your topology.

The theory behind that decision is that topology changes, quite frequently in some cases. So it'd be good to have new stuff pulled in automatically, but we don't want to lose the speeds you've defined (there really is no good way to figure that out, since you might have load-balancing, ECMP, fail-overs, etc.)

Hope this is helpful!
Herbert

**Comment by rchac** [comment]
Herbert, thank you so much for contributing this. This is fantastic. I have modified the README to direct users to use your UISP integration. I really appreciate you taking the time to create this.
