### ISSUE TITLE
Install LibreQoS and dependencies v1.1

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#15]
Install LibreQoS and dependencies

On running the below commands i get some warning

python3 -m pip install ipaddress schedule 'influxdb-client[ciso8601]' requests
sudo python3 -m pip install ipaddress schedule 'influxdb-client[ciso8601]' requests

WARNING: influxdb-client 1.26.0 does not provide the extra 'ciso8601'

Anything to be worried of?

**Comment by rchac** [comment]
It should proceed to install without the ciso8601 variation. I will correct the documentation. Thank you for reporting.
