### ISSUE TITLE
Install PPing + libtins v1.1

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#16]
on changing Dir
cd build
then run

cmake ../ -DLIBTINS_BUILD_SHARED=0 -DLIBTINS_ENABLE_CXX11=1 \
 -DLIBTINS_ENABLE_ACK_TRACKER=0 -DLIBTINS_ENABLE_WPA2=0 \
 -DCMAKE_INSTALL_PREFIX=`dirname $PWD`

i get below errors of 

-- Could NOT find Boost (missing: Boost_INCLUDE_DIR)
-- Disabling ACK tracking support
CMake Warning at CMakeLists.txt:184 (MESSAGE):
  Disabling TCP stream custom data support as boost.any was not found

-- Could NOT find Boost (missing: Boost_INCLUDE_DIR regex)
CMake Warning at examples/CMakeLists.txt:27 (MESSAGE):
  Disabling HTTP requests example since boost.regex was not found

-- googletest git submodule is absent. Run `git submodule init && git submodule update` to get it
-- Configuring done
-- Generating done
-- Build files have been written to: /home/manager/LibreQoS/v1.1/pping/libtins/build

I run
Run `git submodule init && git submodule update` to get it fixed googletest but the missing Boost_INCLUDE_DIR still at large

-- Could NOT find Boost (missing: Boost_INCLUDE_DIR)
-- Disabling ACK tracking support
CMake Warning at CMakeLists.txt:184 (MESSAGE):
  Disabling TCP stream custom data support as boost.any was not found

-- Could NOT find Boost (missing: Boost_INCLUDE_DIR regex)
CMake Warning at examples/CMakeLists.txt:27 (MESSAGE):
  Disabling HTTP requests example since boost.regex was not found

**Comment by rchac** [comment]
To my understanding those errors do not impact functionality for our use. [PPing suggests](https://github.com/pollere/pping)
```
pping uses only the core functions of libtins so, if there are no other users, a static version of the library with fewer dependencies (only cmake and libpcap) can be built and 'installed' in its own source directory:
```
You should still be able to successfully build libtins. Were you able to?

**Comment by mwangi-kiboi** [comment]
yes i was able to.
