### ISSUE TITLE
WIKI Instalation procedure update & maybe installer (?)

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#164]
Please move requirement "influxdb-client" and webapp components like: "flask flask_restful flask_httpauth" and "graphviz" to another step in "(Recomended)" point as it's not needed when we don't use InfluxDB.

**Comment by thebracket** [comment]
We should probably take a step back and consider generalizing the stats system a bit, if we're going to start supporting additional targets for statistics delivery. It'd be nice to avoid huge chains of "if" statements when people also ask for Observium, OpenNMS, Icinga, etc. - as well as the internal discussions about building a better GUI, which would benefit from this also.

**Comment by rchac** [comment]
Good point. I think a unified GUI that interfaces with influxdb on the backend is the ideal solution. Maybe it's too premature to try to add other external DBs until that's solidified.

**Comment by interduo** [comment]
I close this issue as wiki is updated. I will write zabbix integration in other issue.
