### ISSUE TITLE
v1.0 installation service start issue

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#18]
i have done clean install for v1.0 all goes ok.
If i do one time run i get some missing
sudo python3 ./LibreQoS.py see attahced LibreQoS.py.txt not shapping happens

if i run as a service the service doesnt start exots with below error

manager@libreqos:~/LibreQoS/v1.0$ sudo systemctl start LibreQoS.service
manager@libreqos:~/LibreQoS/v1.0$ sudo systemctl status LibreQoS.service
× LibreQoS.service
     Loaded: loaded (/etc/systemd/system/LibreQoS.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-03-04 19:25:06 UTC; 4min 43s ago
    Process: 2864 ExecStart=/usr/bin/python3 /home/$USER/LibreQoS/v1.0/scheduled.py (code=exited, status=200/CHDIR)
   Main PID: 2864 (code=exited, status=200/CHDIR)
        CPU: 1ms

Mar 04 19:25:06 libreqos systemd[1]: LibreQoS.service: Scheduled restart job, restart counter is at 5.
Mar 04 19:25:06 libreqos systemd[1]: Stopped LibreQoS.service.
Mar 04 19:25:06 libreqos systemd[1]: LibreQoS.service: Start request repeated too quickly.
Mar 04 19:25:06 libreqos systemd[1]: LibreQoS.service: Failed with result 'exit-code'.
Mar 04 19:25:06 libreqos systemd[1]: Failed to start LibreQoS.service.

don't know shy i cant get this thing up and running well
[LibreQoS.py.txt](https://github.com/rchac/LibreQoS/files/8188335/LibreQoS.py.txt)

**Comment by rchac** [comment]
What kernel version are you using?
Try
```
uname -a
```
to see

**Comment by rchac** [comment]
I figured it out. Please modify LibreQoS.service with
```
sudo nano /etc/systemd/system/LibreQoS.service
```
Please replace $USER with your actual username, because otherwise when the root user executes it, it will look in the wrong directory.

Fixed documentation to include this disclaimer for both v1.0 and v1.1. Before it only had the disclaimer for v1.1.

**Comment by mwangi-kiboi** [comment]
uname -a
Linux libreqos 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mwangi-kiboi** [comment]
It works when i replace $USER with your actual username

sudo systemctl start LibreQoS.service
manager@libreqos:~/LibreQoS/v1.0$ sudo systemctl status LibreQoS.service
● LibreQoS.service
     Loaded: loaded (/etc/systemd/system/LibreQoS.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-03-05 09:44:12 UTC; 3s ago
   Main PID: 9703 (python3)
      Tasks: 1 (limit: 4470)
     Memory: 6.1M
        CPU: 413ms
     CGroup: /system.slice/LibreQoS.service
             └─9703 /usr/bin/python3 /home/manager/LibreQoS/v1.0/scheduled.py

Mar 05 09:44:13 libreqos python3[9703]: Adding device CPE-Customer4
Mar 05 09:44:13 libreqos python3[9703]: tc class add dev enp4s0 parent 1:17 classid 18 htb rate 27mbit ceil 125mbit prio 3
Mar 05 09:44:13 libreqos python3[9834]: Error: Failed to find specified qdisc.
Mar 05 09:44:13 libreqos python3[9835]: RTNETLINK answers: No such file or directory
Mar 05 09:44:13 libreqos python3[9836]: Error: Failed to find specified qdisc.
Mar 05 09:44:13 libreqos python3[9837]: iphash_modify() IP:100.126.0.80 key:0x50007E64 TC-handle:0x10018
Mar 05 09:44:13 libreqos python3[9838]: RTNETLINK answers: No such file or directory
Mar 05 09:44:13 libreqos python3[9839]: Error: Failed to find specified qdisc.
Mar 05 09:44:13 libreqos python3[9840]: RTNETLINK answers: No such file or directory
Mar 05 09:44:13 libreqos python3[9841]: Error: Failed to find specified qdisc.

**Comment by mwangi-kiboi** [comment]
Unfortunately my shapping doesnt work, if i swap the cables i get a timeout.

**Comment by mwangi-kiboi** [comment]
I managed to make it work v1.0 its shapping.

One disclaimer that needs to apear at all the guides is about the supported NIC.
I had a lab with electrical ethernet ports not optical but the nic was a qualcomm and that the reason it was not shapping.
I changed it with an intel one. Am good.

Out to try v1.1

**Comment by rchac** [comment]
I have now corrected the README to clarify that shaping NICs must support multiple TX/RX transmit queues. Specific supported NICs now listed. Thank you for reporting.
