### ISSUE TITLE
Disable Offloading in Guest VM v1.0

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#19]
1. Is the heading correct? **Disable offloading in Guest vm** or Just **Disable offloading** ?

2. while creating a symlink the command gives an error
sudo systemctl **service** enable offloadOff.service
Unknown command verb service.

if i run without the **service** works
sudo systemctl enable offloadOff.service

**Comment by rchac** [comment]
I have now corrected the documentation for all versions. Thank you for reporting.
