### ISSUE TITLE
ispConfig.py interfaces were swapped or documented incorrectly

### ISSUE THREAD

**Issue by iocampomx** [rchac/LibreQoS#2]
Hi @rchac, I guess the documentation in the ispConfig.py related to the **interfaceA** and **interfaceB** is wrong.

**interfaceA** should be core, and **interfaceB** should be edge, or, you have to swap them in the **LibreQoS.py** code.

Please confirm. Thanks!

**Comment by rchac** [comment]
You are 100% correct, my apologies for the mistake. Corrected in README and comments in ispConfig.py
Thank you for catching this and reporting!
