### ISSUE TITLE
Feature request Shape by network

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#20]
I have noted in the Shaper.csv ipv4 is defined as single ip. ie the ip on the customer equipment.
Example if customer routers has 192.168.0.2 the the expected is 192.168.0.2
Could you incorporate a way of shaping by network like ipv6 (/64)?
like the ipv4 field would take in **192.168.0.0/30** covers 192.168.0.0-192.168.0.3

**Comment by rchac** [comment]
I thought it would work with CIDR already. Does it fail when you try a subnet such as 192.168.0.0/30? Does it provide any error log on a one-time run? (sudo python3 LibreQoS.py)

**Comment by mwangi-kiboi** [comment]
It doesnt work.  its is shaped like Traffic from devices not specified in Shaper.csv

**Comment by rchac** [comment]
Gotcha. This is apparently a limitation of [xdp-cpumap-tc](https://github.com/xdp-project/xdp-cpumap-tc) which LibreQoS uses to redirect traffic to specific qdiscs.

As a kind of hack workaround, we could have LibreQoS add individual /32s for each host in a provided subnet, such as the 4 hosts in a /30. To prevent a situation where a user adds a massive subnet, like a /20, which could limit performance with thousands of rules, I'd probably have it only accept a /24 or smaller. If we used this workaround to make it possible to use /24 or smaller subnets, would that solve the problem for your use case?

If not, and you need /23 or greater, we should instead request proper subnet support in the [issues](https://github.com/xdp-project/xdp-cpumap-tc/issues) page for xdp-cpumap-tc.

**Comment by rchac** [comment]
Feature added in v1.1
