### ISSUE TITLE
Install PPing + libtins v1.1 Guide

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#21]
cd home/$USER/LibreQoS/v1.1/pping/ should be cd **/home/$USER/LibreQoS/v1.1/pping/**
after runing make
make

i get below error

cd /home/$USER/LibreQoS/v1.1/pping/
manager@libreqos:~/LibreQoS/v1.1/pping$ make
**g++ -I/home/manager/src/libtins/include -std=c++14 -g -O3 -Wall -o pping pping.cpp -L/home/manager/src/libtins/lib -ltins -lpcap
pping.cpp:73:10: fatal error: tins/tins.h: No such file or directory
   73 | #include "tins/tins.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: pping] Error 1**

tried to locate tins/tins.h and mine is here /home/manager/LibreQoS/v1.1/pping/libtins/include/

Where should i  correct the dir path?

**Comment by rchac** [comment]
Thank you for reporting. I have changed the guide to correct this. You have to modify the pping Makefile. More details [here](https://github.com/rchac/LibreQoS/wiki/LibreQoS-v1.1-Installation-&-Usage-Guide-Physical-Server-and-Ubuntu-21.10).
