### ISSUE TITLE
Install InfluxDB v1.1

### ISSUE THREAD

**Issue by mwangi-kiboi** [rchac/LibreQoS#22]
upon runing 

wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.1.1-xxx.deb

i get 

--2022-03-07 14:47:55--  https://dl.influxdata.com/influxdb/releases/influxdb2-2.1.1-xxx.deb
Resolving dl.influxdata.com (dl.influxdata.com)... 52.84.45.49, 52.84.45.16, 52.84.45.36, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|52.84.45.49|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-07 14:47:56 ERROR 404: Not Found.

**Comment by rchac** [comment]
Please follow the steps at [https://portal.influxdata.com/downloads/](https://portal.influxdata.com/downloads/)
I have updated the guide to reflect this.

**Comment by mwangi-kiboi** [comment]
wordked. i got Influx up imported the dash board. even created api key but no data on influx db

**Comment by rchac** [comment]
Gotcha. Did you enter the API key for influxDBtoken on ispConfig.py? Is graphingEnabled = True?

**Comment by mwangi-kiboi** [comment]
yes key is set and graphing too. See below though key has be cut out for posting here

#Graphing
graphingEnabled = True
ppingLocation = "pping"
influxDBurl = "http://localhost:8086"
influxDBBucket = "libreqos"
influxDBOrg = "Solutions Ltd"
influxDBtoken = "xxxxxxxxxxxx"

**Comment by rchac** [comment]
Did you create a bucket called libreqos using the InfluxDB web UI? Data > Buckets > Create Bucket

**Comment by mwangi-kiboi** [comment]
Yeah I did.
