### ISSUE TITLE
Unable to get base installation working

### ISSUE THREAD

**Issue by axonxorz** [rchac/LibreQoS#23]
Hey there, I have followed the instructions for a v1.0 installation. I've modified `ispConfig.py` with my relevant interfaces, but am receiving several errors.

Configuration: Ubuntu Server 21.10 running in a KVM/QEMU container. Both interfaces are of type `virtio`, but with no additional configuration in the hypervisor. This configuration is for testing, it will also be tested on a Proxmox and ESXi-based VM, as well as bare metal before going into hopeful production with any of those configurations.

[Log output of running `LibreQoS.py`](https://gist.github.com/axonxorz/015f99e286214ec5c463253ac29adde7)

Of note are:

- Errors in `xps_setup.sh` when trying to write to the relevant queue configuration file in `/sys/class/net/[iface]/queues/[queue]/xps_cpus` (Lines 11-12)
- Errors loading the BPF program into the kernel (Lines 13 and 55)
- Error configuring the `mq` qdisc (starts on line 102).

Manually trying to install the `mq` qdisc with `tc qdisc replace dev enp1s0 root mq` returns the same `RTNETLINK answers: Operation not supported`

**Comment by rchac** [comment]
For v1.0, when running in a VM, please make sure the virtio interfaces in your hypervisor are configured with multiqueue, having the same number of queues as CPU cores allotted to the guest VM. I suspect that is the issue.

Please ensure you have multiple queues by using ethtool inside the VM https://serverfault.com/questions/772380/how-to-tell-if-nic-has-multiqueue-enabled

-------- Original Message --------

**Comment by axonxorz** [comment]
That seems to have done it, though I'm still receiving the errors related to the[ BPF program](https://gist.github.com/axonxorz/015f99e286214ec5c463253ac29adde7#file-log-txt-L13-L54), can these be ignored?

Thanks so much!

**Comment by rchac** [comment]
Hey my apologies for missing this. What errors did you get? The ones pertaining to the build process for pping can be safely ignored.
