### ISSUE TITLE
FYI: BPF-based pping

### ISSUE THREAD

**Issue by tohojo** [rchac/LibreQoS#24]
Just wanted to note (since you added pping support) that we're working on a BPF-based version of pping. Being BPF-based it has lower overhead than the original libpcap-based implementation and it's explicitly targeting an always-on usecase for inline monitoring of latency.

https://github.com/xdp-project/bpf-examples/tree/master/pping

It's still a work in progress, but the current implementation is functional, and has an output format that is compatible with the original pping (and ppviz). There's also an opportunity to adapt the output format or operating mode to your needs; feedback welcome!

Cc @simosund as he's the one writing the code :)

**Comment by rchac** [comment]
Thank you very much for making us aware of this BPF-based alternative. This would be much better suited for our use case and should reduce the CPU overhead greatly. Thank you! I will test this on my network and if it's working well with LibreQoS and existing XDP/BPF code for xdp-cpumap-tc I will transition v1.1-alpha over to using it. Thanks!

**Comment by tohojo** [comment]
You're welcome - thought it might! As I said, may be a bit rough around the edges still, so do let us know if you run into any issues! :)
