### ISSUE TITLE
lacp over bonding interface

### ISSUE THREAD

**Issue by micron10** [rchac/LibreQoS#25]
Hi
is it possible to run LibreQOS over bonding interface 

config is: 

bond0.0100 - uplink internet

bond.0xxx - ussr vlans

and user is connect over ppp connections

**Comment by rchac** [comment]
LibreQoS, like any in-line middle-box (Paraqum, Preseem) needs a single linux bridge to operate on. If you create a bridge between bond0.0100 and bond.0xxx it might work. Without seeing your configuration firsthand I cannot say for certain, but if you are able to get it to work by placing a bridge between those two bonded interfaces please let us know.
