### ISSUE TITLE
AP Shaping

### ISSUE THREAD

**Issue by TekniD** [rchac/LibreQoS#3]
Hi, are you planning on adding shaping to AP side in future?

**Comment by rchac** [comment]
Hello. Yes, that is planned to be added soon. I'm thinking of having a CSV with the name of each AP (corresponding to AP column in shaper.csv) and that AP's max bandwidth. HTBs would be created per AP with sub-HTBs per sub, or just by sub in cases where an AP is not listed for that sub. Will try to work on this soon.

**Comment by rchac** [comment]
AP shaping added in v0.80
