### ISSUE TITLE
Lower CPU usage a bit

### ISSUE THREAD

**Issue by thebracket** [rchac/LibreQoS#30]
It's quite likely that on a decent sized network you'll have some unmapped IPs; the system handles these with the default queues - so that's ok. The `xdp_cpumap` setup defaults to logging every single one of them in the kernel debug stream, which is pretty inefficient.

Take a look at `/sys/kernel/debug/tracing/trace_pipe`:

```
cat /sys/kernel/debug/tracing/trace_pipe
```
You'll have to hit `ctrl` + `c` to stop it, since you're catting a pipe that doesn't have an end. If you have some unmapped IPs generating traffic, you'll see loads of the following:

```
          <idle>-0       [007] d.s3. 1997240.991310: bpf_trace_printk: (xdp) cant find default cpu_idx_lookup

          <idle>-0       [007] dNs3. 1997240.991348: bpf_trace_printk: (tc) Misconf: FAILED lookup IP:0x3c1fc340 ifindex_ingress:2 prio:0
```

The BPF program is writing every single one of them to the kernel debug stream. That's a fast operation, but unless you actually plan on reading this file it's pretty unnecessary (and you can figure out unmapped IPs pretty well with the latency handler).

You can not emit these messages:

1. Open `src/tc_classify_kern.c` in the `xdp-cpumap` project.
2. Find line 103, which will read `#define DEBUG 1`
3. Comment it out - so `// #define DEBUG 1`
4. Save and exit your editor
5. Run `make` to rebuild the BPF program
6. Restart your shaper to load the new program.

You'll no longer see a flood of debug messages in the kernel trace log, and CPU time (and more importantly cache) is no longer used up creating these messages and storing them in the kernel trace pipe.

(You can also edit `Makefile` and change `CC := gcc` to `CC += gcc -O3` for a quick'n'dirty change to the original `Makefile` that enables maximum CPU optimization on the BPF program. You might get `-Os` (optimize for size) running faster - or have to use it if you extend the BPF program since they have a limit of 4096 bytes.)

**Comment by thebracket** [comment]
Update: testing this, it also helps to do the same for `xdp_iphash_to_cpu_kern.c`

**Comment by Belyivulk** [comment]
Was this ever committed, or is it still a thing?

**Comment by Belyivulk** [comment]
Nvm, found that in tc_classify_kern.c but not xdp_iphash_to_cpu_kern.c

**Comment by interduo** [comment]
This should go to xdp-cpumap-tc as issue also.

**Comment by rchac** [comment]
Is this still an existing issue in xdp-cpumap-tc? We can make an issue there if needed.

**Comment by interduo** [comment]
> Is this still an existing issue in xdp-cpumap-tc? We can make an issue there if needed.

In xdp-cpumap-tc there is a debug turned on by default. So Yes

**Comment by thebracket** [comment]
Debug is on, but in the most recent build it won't spit out messages unless
it actually has something to tell you. Turning off debug won't gain you
much (in my quick benchtest, no difference whatsoever).

**Comment by thebracket** [comment]
We also settled on O2 optimization. Os may be needed if cpumap keeps growing, and O3 turned out to occasionally give odd results. I think I can close this issue, because the large items are done.
