### ISSUE TITLE
How to utilize multiple NIC

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [rchac/LibreQoS#33]
I have 2 pcie cards both cards have 2 sfp slots. How to utilize that ?
should i add all interface to bridge0 or create a new bridge and add other ports there.
Or it can be utilized seperately ?

**Comment by muhammadarsalansiddiqui** [comment]
I can assume it is possible to bond card 1 ports and card 2 ports then add these in bridge, but can we seperate this ? as we might have different wan and it should create a problem

**Comment by rchac** [comment]
Libre does not support multiple NICs in that way. I am not aware of any QOE product that does. You only need two shaping interfaces. One NIC with dual SFPs is sufficient. Bonding is not recommended and would cause major issues.
