### ISSUE TITLE
A thought

### ISSUE THREAD

**Issue by Belyivulk** [rchac/LibreQoS#39]
Hi LibreQoS fam!

I've been pondering on the very high CPU loading we had at the very beginning of our initial test of LibreQoS and wondered if there might be improvements to be had in the default config.

In order for us to test (and i stress, test) shaping by Site or AP we had to route *all* of our traffic through the box; with only a handful of AP's and clients defined in the Shaper.CSV. During this phase our CPU loading was as high as 70% per core across all cores (once we got there). Once all clients were defined in the shaper.csv and had parent sites, this loading has dropped to a maximum of 30%. In both cases we were observing a touch over 11gig/sec running through the box; so if there was heavy shaping going on, it wasn't apparent.

I'm not very clear on the underlying cause; i thought initially its because XDP wouldn't touch those clients who were undefined, causing their traffic to touch the linux kernel, but idk - it's not my area of expertise. In any event given the fix for us was to define every user in shaper.csv; I wonder if in the configuration it would be useful to have a "testing" section (which can be commented out for production) or similar that gets the admin to specify the subnet's they're going to route through the box, an upper limit of what a client should be able to achieve in terms of UL/DL (this is per IP) and then create a queue for each IP within that subnet? 

Or there may be a much simpler / sexier fix? Look forward to your thoughts!

**Comment by rchac** [comment]
I think it's probably due to unspecified traffic defaulting to core 0 and a single queue - as a result of xdp-cpumap-tc tying queues to CPU cores.

And I think that would be a great feature. So basically in ispConfig.py the user could define
```
shapedSubnets = [[IPv4Network('100.64.0.0/22'),IPv4Network('192.168.100.0/24')]
shapedSubnetsMbpsDownMax = 100
shapedSubnetsMbpsUpMax = 100
shapedSubnetsMbpsDownMin = 25
shapedSubnetsMbpsUpMin = 25
```
and for any IPs not specifically defined in Shaper.csv, but within those subnets, traffic could be shaped according to those limits. We could create tins, equal to the number of CPUs/queues, and evenly distribute IPs from these subnets among them.

If that would solve what you have in mind let me know.

**Comment by Belyivulk** [comment]
I think that would do it; although the documentation / comments would need to be clear as to which functions to use when and why; so that we don't end up with unintended consequences. Happy to help on that front if helpful

**Comment by rchac** [comment]
Added feature in v1.2: Automatic creation of Parent Nodes for device without listed Parent Node
