### ISSUE TITLE
Using HTB more efficiently with cburst and burst

### ISSUE THREAD

**Issue by dtaht** [rchac/LibreQoS#40]
I have been looking over my first major libreqos installation elsewhere and reviewing the code a bit. I am mostly familiar only with cake and with htb + fq_codel as in the sqm-scripts, and after looking over a ton of packet captures over a busy wireless network, I have a possible optimization for some (wifi) networks in mind, that I'd like (others!) to try out at a smaller scale.

HTB has a burst and cburst parameter that limit the size of how many packets can be dequeued from a given htb tier at a time. Our original use for it, in the SQM scripts, was to lighten the CPU load (and lower locking issues) on low end hardware. In  the ISP case, as you scale, that problem could also become an issue, but more efficiently using the bandwidth within the packet aggregation that wifi does, is what I'm trying to describe today. 

Basically wireless-n wifi can take about 240us to switch between stations and a txop can take up to 5.7ms, you can pack up to 42 packets or 64k into a single aggregate depending on your mcs rate. This gets hairier and hairier with ac and later (and I essentially advertise a TXOP in the beacon of 2ms or less)... sticking with the 802.11n model for points of illustration... 

It's really inefficient to send 1 packet (which can take, 10us!) then switch. It's also very noticible with 20 stations, to be taking 5ms each, so a decent compromise is to aim for, say, 500us of multiplexing, figure out how many packets and data can fit into that at the mcs rate you have, and burst that amount out of the shaper. 

So I am considering modifying *all* the classes to also include the burst and cburst parameters (without bothering too much to figure out what the right size is as yet), and if there is anyone out there willing to fiddle in a simplified scenario (one AP + 2-4 stations + cake on the the flent rtt_fair test) to show if even this simple change has benefit at high contention, or is daring enough to just deploy it, give it a shot. 

shell('tc class add dev ' + interfaceA + ' parent ' + parentClassID + ' classid ' + str(minor) + ' htb rate '+ str(round(elemDownloadMin)) + 'mbit ceil '+ str(round(elemDownloadMax)) + 'mbit ' + ' burst 3028 cburst 3028 ' + ' prio 3') 

PS As ghu is my witness I do not know what the differences really are vs a vs burst and cburst. Maybe cburst or burst alone is enough.   Figuring out the right number to pack into an aggregate is hard, and perhaps on a good network, at short ranges, a much larger burst would show a demonstrable effect. 

PPS Over here there's an 8 minute segment that explains the problems aggregation introduced into multi-station wifi multiplexing. We solved that by intelligently creating backpressure "at the line rate", and scheduling at the AP better, but if you are artificially limiting the bandwidth to the radios, accounting for aggregation in the shaper might help. 

https://www.youtube.com/watch?v=Rb-UnHDw02o&t=1560

**Comment by rchac** [comment]
Hey Dave. Thank you for bringing this up and providing a possible solution. I will go ahead and test this in production as soon as I can. Thanks!

**Comment by rchac** [comment]
![change](https://user-images.githubusercontent.com/22501920/182503156-475c62db-606c-48c9-96ae-1a4d1381af32.png)

**Comment by rchac** [comment]
![waveform](https://user-images.githubusercontent.com/22501920/182504121-b80170e9-aade-4ee6-8250-fc82bb7b1d7e.jpeg)

**Comment by dtaht** [comment]
It looks like a modest win. (in the future, it helps to title the plots -t the_options_under_test) So what I'd do is change the code to
allow the BURST and CBURST variables to be set by in the config, defaulting to 3028, then set the classes to use those (instead of what I hard coded above) in the code and point users in the script at this github issue.

I don't know if that improvement in slow start (reducing the impact of it in the first few seconds) you are showing is to be believed or not, 10 runs, separated by a few seconds, aggregated together might be more revealing. If it's is real, my theory would be it allows for a more accurate tcp rtt estimate in the early phase of the test... and that we should begin considering bigger quantums in cake itself at higher rates. 

The problem is that wifi has a limit on "number of packets" as well as "data", and it grows and shrinks relative to your mcs rate, (and a few other variables - see ongoing work at: https://forum.openwrt.org/t/reducing-multiplexing-latencies-still-further-in-wifi/133605/15 ) so at mcs-12 (on n) for example, you could fit in 8k or 20 packets. HTB only allows you to limit dequeuing from a bucket (essentially per customer with cake) by bytes, and then cake switches between flows based on the quantum. Anyway - for a base config - 3028 seems like a good compromise value - two big tcp packets, or a mix of a tcp and other packets, or a bunch of acks... it saves on cpu, it mimics real world tcp senders...

ac (and later) lets you send 4MB! and 96 (or more I forget) packets in a single burst. I would in general prefer ac just adopt fq_codel for wifi directly.

**Comment by dtaht** [comment]
Well, we tried it on a busy pre-wireless-n network... and it was awful. So making the idea available for further testing makes sense, but the default where htb autoscales these quantities should remain the default.

**Comment by rchac** [comment]
Thank you for letting me know! Also sorry for delayed response - got COVID and was out of commission for a while.

**Comment by interduo** [comment]
man tc-htb shows:

```
       burst bytes
              Amount  of  bytes  that can be burst at ceil speed, in excess of
              the configured rate.  Should be at least as high as the  highest
              burst of all children.

       cburst bytes
              Amount  of bytes that can be burst at 'infinite' speed, in other
              words, as fast as the interface can transmit them.  For  perfect
              evening  out,  should  be  equal  to at most one average packet.
              Should be at least as high as the highest cburst  of  all  chil‐
              dren.

       quantum bytes
              Number  of  bytes  to serve from this class before the scheduler
              moves to the next class.  Default value is rate divided  by  the
              qdisc r2q parameter.  If specified, r2q is ignored.
```
I think it could be set globally not per ShapedDevices.csv row.
Tuning burst speed values is very important for small tariffs <20Mbits in aspects of website loading and some speedtests ;-)
