### ISSUE TITLE
no git in ubuntu minimal install

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#43]
In instruction: https://github.com/rchac/LibreQoS/wiki/LibreQoS-v1.1-Installation-&-Usage-Guide-Physical-Server-and-Ubuntu-21.10

Instead of
```
git clone https://github.com/rchac/LibreQoS.git
sudo apt update
sudo apt install python3-pip clang gcc llvm libelf-dev
python3 -m pip install ipaddress schedule prettytable
sudo python3 -m pip install ipaddress schedule prettytable
```

Should be:
```
sudo apt update
sudo apt install python3-pip clang gcc llvm libelf-dev git nano
python3 -m pip install ipaddress schedule prettytable
sudo python3 -m pip install ipaddress schedule prettytable
git clone https://github.com/rchac/LibreQoS.git
```

Good thig is to have `unattended-ubuntu-22.04-install.sh` file for any of that kind of projects - this will help in future testing/developing.

**Comment by rchac** [comment]
Thank you. I have updated the v1,.1 documentation to include git and nano as dependencies for ubuntu-minimal installs, and placed the git clone command at the end.
