### ISSUE TITLE
Subscriber - support two IP addresses (not in the same subnet)

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#46]
> Yup! just put 192.168.1.55/29 as the IPv4 in Shaper.csv for your customer.

The main thing is that LibreQoS not support getting different IPs from 192.168.1.2/24 and 192.168.2.2/24 and mark it as one flowid and limit into one queue :( Is it hard to implement this?

> I suppose the best way to implement this would be to add a customer_ID field on Shaper.csv (in addition to the existing ID field). With that, if multiple entries in Shaper.csv share the same ID, they can be in the same queue.

This is the case for two main cases:
1. Subscriber have 2 publics IPs and one service,
2. Some LXC containers got two ip addresses from different VLANS and two gateways depending on conditions the routing is getting through one or second ip.

> That makes sense. Let's work to add this functionality.

This is a blocker for us to use LibreQoS now for production.

**Comment by rchac** [comment]
So I'm thinking of adding a "HostGroupID" field to Shaper.csv. If a client has two IPs for the same client/service location, each could be defined with the same HostGroup ID # and be placed into the same queue/qdisc. Entries without any HostGroup ID # would be individually handled. Would that work for your use case?

**Comment by interduo** [comment]
Yes - that is it.
My little suggestion is only to name this as "CustomerServiceID" (many Devices/CRMs use HostGroupID for different thing)

**Comment by interduo** [comment]
The important thing is also to have statistics per CustomerServiceID/HostGroupID.

**Comment by interduo** [comment]
@rchac do You know when will You code that?

I am asking about this because I would like to test LQoS in real envirnoment and this is the only thing whitch blocks me from that. I feel like 'Curious George' now everytime I log into LibreQoS VM ;)

**Comment by interduo** [comment]
@rchac do You know when will You code that?

I am asking about this because I would like to test LQoS in real envirnoment and this is the only thing whitch is blocking me from that. 

I feel like 'Curious George' only having LibreQoS on my VM ;)

**Comment by interduo** [comment]
Check if row contains `CustomerServiceID` (first test) and then check if `CustomerServiceID` was set in `Shaper.json` (second test) in earlier rows (https://github.com/rchac/LibreQoS/blob/main/v1.1/LibreQoS.py#L177 - bellow this line is good place for that)

- if its the first occurance of `CustomerServiceID` (second test is false), save it into some variable of type array(CustomerServiceID, major, minior) for future use,
- if its the next usage (second test if true) get the minor and major number from array and create variable nextUsage = 1,

Then bellow:
- nextUsage is 1 then ommit adding qdisc/class here
(https://github.com/rchac/LibreQoS/blob/main/v1.1/LibreQoS.py#L187-L193)

This idea for implementation seems to be simple.

@rchac what do You think about it? I use PHP not python, could You help in implementing that?

**Comment by rchac** [comment]
@interduo Started working on it this morning. Here's a rough alpha version of 1.2 with support for multiple devices/IPs per subscriber circuit. https://github.com/rchac/LibreQoS/tree/main/v1.2

I had to change from assuming a single device to assuming "circuits" which can have multiple devices and fall within one queue.

If an entry in ShapedDevices.csv has the same Circuit ID as another before it, it will be added to that circuit.

**Comment by rchac** [comment]
You only need to list the Circuit ID for a device if its circuit has multiple devices. If a Circuit ID is not listed for a device in ShapedDevices.csv, LibreQoS assumes it is it's own circuit. So for most entries in ShapedDevices.csv they can have CircuitID blank if they don't have other devices in the same circuit.

You can change the order of rows however you like, it's not a problem.
-------- Original Message --------

**Comment by interduo** [comment]
If some customer got two ip's and in Shaper.json got some mistake (different speeds per class). Do LibreQoS rise an error or just use first definition for Circuit?

**Comment by rchac** [comment]
It will use the first bandwidth download/upload definition it sees for that circuit. If it would help, we can make it check for different rates and raise an error if they are different.

**Comment by interduo** [comment]
Warning it would be better than error.

**Comment by rchac** [comment]
Done. https://github.com/rchac/LibreQoS/commit/a3ce20ba0de9cd8b73f8871873f437a3014912f5

**Comment by interduo** [comment]
testing and got an error:

```
root@rty-libreqos:~/LibreQoS2/v1.2# python3 LibreQoS.py
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 88
    "devices" = deviceListForCircuit
            ^
SyntaxError: ':' expected after dictionary key
```

root@rty-libreqos:~/LibreQoS2/v1.2# cat ShapedDevices.csv 
```
Circuit ID,Circuit Name,Device ID,Device Name,Parent Node,MAC,IPv4,IPv6,Download Min,Upload Min,Download Max,Upload Max
,"CID100",3,"NODEID567",AP_A,,100.64.0.2,,25,5,105,18
2000,"CID1456",3,"NODEID2345",AP_A,,100.64.0.3,,25,5,105,18
2000,"CID1456",3,"NODEID3456",AP_A,,100.64.0.4,,25,5,105,18

```

**Comment by rchac** [comment]
Sorry about that. [Corrected](https://github.com/rchac/LibreQoS/commit/84122f6f9f8be553e2d6df353c288d52dacd89a4).

**Comment by interduo** [comment]
More is here:
```
root@rty-libreqos:~/LibreQoS2/v1.2# python3 LibreQoS.py
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 92
    "downloadMin": round(int(downloadMin)*tcpOverheadFactor),
    ^^^^^^^^^^^^^
SyntaxError: invalid syntax
```

**Comment by interduo** [comment]
> It will use the first bandwidth download/upload definition it sees for that circuit. If it would help, we can make it check for different rates and raise an error if they are different.

This makes an error of:
```
/root/LibreQoS2/v1.2/LibreQoS.py:60: UserWarning: Device NODEID3456 with ID 3 had different bandwidth parameters than other devices on this circuit. Will instead use the bandwidth parameters defined by the first device added to its circuit.
  warnings.warn("Device " + deviceName + " with ID " + deviceID + " had different bandwidth parameters than other devices on this circuit. Will instead use the bandwidth parameters defined by the first device added to its circuit.")
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 301, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 129, in refreshShapers
    network = json.loads(j.read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 70 (char 71)
```

**Comment by interduo** [comment]
```
# python3 LibreQoS.py
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 301, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 51, in refreshShapers
    circuitID, circuitName, deviceID, deviceName, ParentNode, mac, ipv4, ipv6, downloadMin, uploadMin, downloadMax, uploadMax = row
ValueError: not enough values to unpack (expected 12, got 11)
```

This error could print line number or just print whole line.

**Comment by interduo** [comment]
```
root@rty-libreqos:~/LibreQoS2/v1.2# cat network.json ShapedDevices.csv 
{
	"AP_A": { "downloadBandwidthMbps":4000,	"uploadBandwidthMbps":4000, },
	"AP_B": { "downloadBandwidthMbps":4000,	"uploadBandwidthMbps":4000, },
	"AP_C": { "downloadBandwidthMbps":4000,	"uploadBandwidthMbps":4000, },
	"AP_D": { "downloadBandwidthMbps":4000,	"uploadBandwidthMbps":4000, }
}
Circuit ID,"Circuit Name",Device ID,"Device Name",Parent Node,MAC,IPv4,IPv6,Download Min,Upload Min,Download Max,Upload Max
,"CID100",1,"NODEID567",AP_A,,100.64.0.2,,25,5,105,18
2000,"CID1456",2,"NODEID2345",AP_A,,100.64.0.3,,25,5,105,18
2000,"CID1456",3,"NODEID3456",AP_A,,100.64.0.4,,25,5,105,18

```

**Comment by interduo** [comment]
Doesn't help that.

**Comment by interduo** [comment]
Yes I noticed that. Now we are going further...

**Comment by rchac** [comment]
The majority of those errors are benign but ```UnboundLocalError: local variable 'device' referenced before assignment``` is not. Let me work on that one moment.

**Comment by rchac** [comment]
Could you please try with https://github.com/rchac/LibreQoS/commit/8b3db72d024f26d0092ff907ce57c1b4c2290bbb

**Comment by interduo** [comment]
```
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 303, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 288, in refreshShapers
    for device in devices:
NameError: name 'devices' is not defined. Did you mean: 'device'?

```

**Comment by interduo** [comment]
```
root@rty-libreqos:~/LibreQoS2/v1.2# git fetch origin
root@rty-libreqos:~/LibreQoS2/v1.2# git pull origin main
From https://github.com/rchac/LibreQoS
 * branch            main       -> FETCH_HEAD
Already up to date.
```

**Comment by rchac** [comment]
Making progress. How is it with https://github.com/rchac/LibreQoS/commit/e726ac754bc73617a6a4e4adee23f6ce3f30ac02 ?

**Comment by rchac** [comment]
1) Those warnings do not stop it from working, it's some libbpf thing but should not impact functinality
2) Those errors are benign. They appear because the qdiscs havent been made yet. It clears existing qdiscs and classes on each load.

**Comment by interduo** [comment]
1. Nice to know.
2. I know that but maybe some check should be done in script?

**Comment by rchac** [comment]
Yeah it's the parsed console output response from Linux Traffic Control. Basically that's Linux TC saying "we can't make that change to that item". It won't show all that after the first run.

**Comment by interduo** [comment]
`tc` command got no option to make quiet those warnings I checked it.

**Comment by rchac** [comment]
Yay! Awesome

**Comment by interduo** [comment]
One more thing - service LibreQoS. If I change the file - how long it takes to regenerate the rules?

**Comment by rchac** [comment]
Usually once you've got ```sudo python3 LibreQoS.py``` working, you'll want to [run it as a service from then on](https://github.com/rchac/LibreQoS/wiki/LibreQoS-v1.1-Installation-&-Usage-Guide-Physical-Server-and-Ubuntu-21.10#running-as-a-service). As a service, you can get graphing to work. Once that's set up I usually use ```sudo systemctl restart LibreQoS.service``` to reload it manually if I know the ShapedDevices.csv has been changed in any way. Running it as a service, it will automatically resresh the queues every morning at 4AM (you can change that time of course). And when the service is restarted it will immediately refresh the queues as well.

And it depends on the number of queues it has to make but usually ~2 seconds.

**Comment by rchac** [comment]
> Is there any "check syntax" validator for ShapedDevices.csv and network.json?

There should be. It's a good feature to add. Technically if those have errors, LibreQoS.py exits before any changes are made to existing queues. Still, let me see how to add that for Network.json first since that's a common pain point for users.

**Comment by interduo** [comment]
I make some more issues for not making this issue trashed.
I think the most important thing is to generate all commands before running them.

Pros are:
- we have startup configs,
- reloading takes less time,
- if we got an error we can "get back" using earlier generated files,

**Comment by interduo** [comment]
As it CircutID is generating good commands I will close that issue. Thanks for commits.

**Comment by rchac** [comment]
Those particular errors are normal, you can disregard them. It's meant to clear settings if qdiscs already exist, which they don't in your case.

**Comment by interduo** [comment]
Why You don't create whole tc-rules-file and then use --batch command only one time?
Maybe this would help for dropping packets when reloading?
