### ISSUE TITLE
HTB: quantum of class 80015 is big. Consider r2q change.

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#53]
When I run LibreQoS.py in dmesg I get an warning: `HTB: quantum of class 80015 is big. Consider r2q change.` is this important? (I don't use HTB since ~10 years)

**Comment by dtaht** [comment]
I appreciate you filing a bunch of individually answerable issues. Most of the error messages in htb date back 20 years, and this case, although we might want to tune the quantum down someday after some testing, is harmless.

**Comment by interduo** [comment]
@rchac did You changed something in code for that issue? I would like to know if this is important or not.

**Comment by dtaht** [comment]
It's not important.
