### ISSUE TITLE
[question] HTB classes design purpose

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#56]
Could HTB subscriber classes be connected to interface root mq classes directly (not site/ap class) when using `ShapeBySite = False` and flat design?

The HTB multiqueue count should be the same as network interface queues and devices could be connected to classes in sequence like this 1, 2, 3, 4, 1, 2, 3, 4....

Less hierarchical classes/nesting level for HTB classes means less work to be done by CPU.

This would really simplified the design in most cases and not break the control over throughput/mq queues.

If I clear AP column in `Shaper.json` and clear `network.json` and leave only parenthis { } - then I get an error:
`Device Device1 was not shaped. Please check to ensure its parent Node is listed in network.json`

If I clear whole network.json I get an error:
```
Traceback (most recent call last):
  File "/root/LibreQoS/v1.1/LibreQoS.py", line 243, in <module>
    refreshShapers()
  File "/root/LibreQoS/v1.1/LibreQoS.py", line 72, in refreshShapers
    network = json.loads(j.read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

So I think I am not able to put subscriber classes connected directly to network multiqueue interface.

NOW:
```
tc qdisc replace dev ens16f0 root handle 7FFF: mq
tc qdisc add dev ens16f0 parent 7FFF:0x1 handle 0x1: htb default 2
tc class add dev ens16f0 parent 0x1: classid 0x1:1 htb rate 14000mbit ceil 14000mbit
tc qdisc add dev ens16f0 parent 0x1:1 cake diffserv4
tc class add dev ens16f0 parent 0x1:1 classid 0x1:2 htb rate 27.0mbit ceil 108mbit prio 5
tc qdisc add dev ens16f0 parent 0x1:2 cake diffserv4
```

BETTER BE SOMETHING LIKE THAT:
```
tc qdisc replace dev ens16f0 root handle 7FFF: mq
tc class add dev ens16f0 parent 7FFF: classid 0x1:1 htb rate 14000mbit ceil 14000mbit
tc qdisc add dev ens16f0 parent 7FFF:1 cake diffserv4
tc class add dev ens16f0 parent 7FFF:1 classid 0x1:2 htb rate 27.0mbit ceil 108mbit prio 5
tc qdisc add dev ens16f0 parent 7FFF:2 cake diffserv4
```
parrent for subscribers should also be changed in other rules to root and not subclass

**Comment by rchac** [comment]
This is done so that multiple top-level ParentNodes can fit into one CPU core. For example, if you have 20 top level sites, but only 4 CPUs, it needs to be able to wrap around and evenly distribute those among CPU cores. Each top-level ParentNode can be placed under an HTB that serves as the top of a CPU core.

**Comment by interduo** [comment]
This is not needed for flat design.

**Comment by rchac** [comment]
That is possible but it would probably have limited or no performance benefit. Even with the current nested HTB design - LibreQoS v1.1 puts through 11Gbps on an Intel Xeon Gold 6258R with just 30% CPU use. That suggests that with a $250 AMD Ryzen 7 5800X 20Gbps or more should be achievable.

I haven't seen anything to suggest removing one HTB layer would reduce CPU use. That said it's still possible. We can certainly make a custom version for you to test to see if it helps at all throughput wise. Are you seeing throughput concerns?

**Comment by interduo** [comment]
> Are you seeing throughput concerns?

Now I've got this kind of design at my scripts writen from the scratch. As I remember it takes down some percent of CPU use.
I warned up about this because I know that changing design is very laborious thing at the middle of codding but less at the begining.

**Comment by rchac** [comment]
That makes sense. We could potentially make a special part of the code for cases where 0 entries in ShapedDevices.csv have any Parent Node listed. I would have to do it as a paid consultation though because it doesn't seem to be crucial for other operators (majority use network.json hierarchy), it would likely have a small CPU impact, and would complicate the code a bit with regard to readability. I'm not opposed to it, I just want to focus on features that best serve all operators, unless its a paid consultation.

**Comment by interduo** [comment]
> I just want to focus on features that best serve all operators

That is so true true true!

I will test what is the impact of additional class level in HTB like we did this when writing HFSC script. If the impact will be big then we could go back here. Don't close for now this issue.

**Comment by rchac** [comment]
That sounds perfect. Appreciate your help with testing that out. I'll leave this issue open.

**Comment by interduo** [comment]
Carefuly analyzed linux_tc.txt and it's not possible to do that in that way I suggested when we use MQ.
I am closing it now.
