### ISSUE TITLE
Network.json and ShapedDevices.csv Validator

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#60]
Is there any "check syntax" validator for ShapedDevices.csv and network.json?
I will be generating big ShapedDevices.csv in my CRM - I need to be completly sure if it completly ok before running the script.

Especialy when there is a crontab at 4 AM :-)

**Comment by rchac** [comment]
This will check if network.json has any obvious JSON syntax errors such as extra commas after last entries. Should help.
https://github.com/rchac/LibreQoS/commit/2ee3510f06a5508e870f27165da2c3505989a662

**Comment by interduo** [comment]
Got some errors when running now.

```
tc qdisc replace dev ens16f0 root handle 7FFF: mq
tc qdisc add dev ens16f0 parent 7FFF:0x1 handle 0x1: htb default 2
Error: Exclusivity flag on, cannot modify.
```

**Comment by rchac** [comment]
> Error: Exclusivity flag on, cannot modify.

This part worries me. Can you post or DM me the full console output when you run ```sudo python3 LibreQoS.py```?

**Comment by interduo** [comment]
@rchac https://gist.github.com/interduo/853b63f59d8ae2888e83f2466fe902d1

**Comment by interduo** [comment]
This could be some race condition issue?

**Comment by rchac** [comment]
What NIC are you using?

**Comment by interduo** [comment]
> What NIC are you using?

```
00:10.1 Ethernet controller: Intel Corporation Ethernet 10G 2P X520 Adapter (rev 01)
	Subsystem: Intel Corporation 10GbE 2P X520 Adapter
	Physical Slot: 16
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin B routed to IRQ 10
	Region 0: Memory at fea80000 (64-bit, non-prefetchable) [size=512K]
	Region 2: I/O ports at e0c0 [size=32]
--
	Kernel driver in use: ixgbe
	Kernel modules: ixgbe
```

**Comment by interduo** [comment]
If I go back to:
`git checkout e726ac754bc73617a6a4e4adee23f6ce3f30ac02` there is no errors like that

**Comment by interduo** [comment]
Its my commit getting those issues. I will change some code.

**Comment by rchac** [comment]
Gotcha. Reverted changes pertaining to muting output of TC. [Updated](https://github.com/rchac/LibreQoS/commit/1fcd22a46f4f53ac4656c602b1967b554b37ba01).

**Comment by interduo** [comment]
Sorry for not catching it earlier.

![image](https://user-images.githubusercontent.com/17087236/188498934-5f0c1afe-6cef-45b2-bd85-e3f4875ca13f.png)

**Comment by rchac** [comment]
No worries, I would not have expected that commit to have that effect at all. It's all good.

**Comment by interduo** [comment]
> No worries, I would not have expected that commit to have that effect at all. It's all good.

Me2 completly - so I pasted this image as reflection of my emotions now hehe

**Comment by rchac** [comment]
As a heads up - I will be away from the computer for a few hours. If anything comes up I will try to help as soon as I'm back.

**Comment by interduo** [comment]
> As a heads up - I will be away from the computer for a few hours. If anything comes up I will try to help as soon as I'm back.

Ok - thanks for the info - I think that most important things now are:
https://github.com/rchac/LibreQoS/issues/52 (SafeGuard for running multipletimes)
https://github.com/rchac/LibreQoS/issues/47 (reloading rules drops packets)

I don't imagine running at prod without the first one (or some workaround like bash wrapper with flock/lockfile).

Now I do my work - write integration with our CRM.

**Comment by interduo** [comment]
@rchac are You planning to write a validator for `ShapedDevices.csv` or it needs to be done around the LibreQoS? Please give a feedback when closing issue.

**Comment by rchac** [comment]
Sorry i was closing out issues and misunderstood. Yes I will write a validator for ShapedDevices.csv as well

**Comment by interduo** [comment]
One more thing here to consider - maybe it would be good thing to allow many IP addresses in one line im double quote instead of setting CircuitID?

What do You think about it?

**Comment by rchac** [comment]
That seems reasonable. In that case, Circuit ID might be superfluous. Let me work on that solution.

**Comment by interduo** [comment]
Sorry for catching the idea after implementation but this comes after making first version of integration with our CRM.

This would also limit possibility of making mistakes.

**Comment by rchac** [comment]
Does this work? https://github.com/rchac/LibreQoS/commit/ba5ce6793832ebb04d6f42496715cf384be4305a

**Comment by interduo** [comment]
@rchac please update te template of ShapedDevices.csv

**Comment by interduo** [comment]
@rchac maybe in line https://github.com/rchac/LibreQoS/commit/ba5ce6793832ebb04d6f42496715cf384be4305a#diff-4af76f2739012586e9d1ef571bbe5fb0286c039b73ab5aee9d5f97f8936948f6R124 it should add /32 for all single hosts?

**Comment by interduo** [comment]
Some more testing:

```
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 62, in refreshShapers
    ipv4_hosts.append(ipaddress.ip_address(ipEntry))
  File "/usr/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: '100.64.0.2/32' does not appear to be an IPv4 or IPv6 address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 397, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 68, in refreshShapers
    raise Exception("Provided IPv4 '" + ipv4_input + "' in ShapedDevices.csv at row " + str(rowNum) + " is not valid.") from e
Exception: Provided IPv4 '100.64.0.2/32' in ShapedDevices.csv at row 2 is not valid.
```

**Comment by rchac** [comment]
Fixed [LibreQoS.py](https://github.com/rchac/LibreQoS/blob/main/v1.2/LibreQoS.py) and [ShapedDevices.csv](https://github.com/rchac/LibreQoS/commit/a7bfe5e9158cd4364da850ac9ada2d4045523dcc). Please let me know if it works for you now.

**Comment by interduo** [comment]
It works.

**Comment by interduo** [comment]
/32 could be just removed ;-)

**Comment by rchac** [comment]
> /32 could be just removed ;-)

Done. https://github.com/rchac/LibreQoS/commit/87962aefa3e34460846c854e134ab7c7e92b098a It just strips '/32' both in validation and actual importing now.

**Comment by interduo** [comment]
One more thing - don't get rows started with `#`

**Comment by rchac** [comment]
Placing a # at the start of some rows is not a very standard way to use CSV files, and would break the ability to open the file using Excel or other editors. Would adding a new "Comment" column at the end of each row be sufficient for your use case?

**Comment by interduo** [comment]
Whole file needs a timestamp in the beggining - we do it always in first line.

**Comment by interduo** [comment]
The additional column in every row for comments it would help in few cases. I suggest to add it as a last column.

**Comment by interduo** [comment]
We need to distinguish file generated from yesterday and generated today. 
(checking file data is not the solution because it change when editing etc)

**Comment by rchac** [comment]
That makes sense. I have updated LibreQoS.py and ShapedDevices.csv. It will check for and skip lines starting with #. Since we now look for a comment field at the end of each csv row, please ensure you have a Comment column in the csv at the end. Please let me know if this helps.

**Comment by interduo** [comment]
I've got one error but i dont know what it comes from:

```
LibreQoS.py | less
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 402, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 383, in refreshShapers
    finalMinor = traverseNetwork(network, 0, major=1, minor=3, queue=1, parentClassID="1:1", parentMaxDL=upstreamBandwidthCapacityDownloadMbps, parentMaxUL=upstreamBandwidthCapacityUploadMbps)
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 349, in traverseNetwork
    shell('tc class add dev ' + interfaceA + ' parent ' + elemClassID + ' classid ' + hex(minor) + ' htb rate '+ str(minDownload) + 'mbit ceil '+ str(maxDownload) + 'mbit prio 3')
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 24, in shell
    print(command)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by rchac** [comment]
Can I see full console output of ```python3 LibreQoS.py```?

**Comment by interduo** [comment]
after updating got:
```
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 414, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/./LibreQoS.py", line 90, in refreshShapers
    ipv6_hosts.append(ipaddress.ip_address(ipEntry))
UnboundLocalError: local variable 'ipv6_hosts' referenced before assignment
```

**Comment by rchac** [comment]
Fixed https://github.com/rchac/LibreQoS/commit/2e44cce1bdd8d4750d14740d16b884fcb9335a2a

**Comment by interduo** [comment]
> Can I see full console output of `python3 LibreQoS.py`?

https://gist.github.com/interduo/a1fd9f84e3d7c95479d568d566da2b9a

**Comment by rchac** [comment]
Great! So it is working now?

**Comment by rchac** [comment]
@interduo Clear to close this issue?

**Comment by interduo** [comment]
I think we could close the issue bugfixes will be in another one.
