### ISSUE TITLE
What is Circuit ID & Circuit Name in v1.2 ?

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#66]

**Comment by rchac** [comment]
Circuit ID would be a shared ID number between different entries in ShapedDevices.csv - all intended to point to the same queue. The intended use case is where a customer location has multiple distinct IPs which need to be fed into the same queue.

If your CRM has "customer location ID" or something similar - that might be a good value to use for Circuit ID. If an entry in ShapedDevices.csv has Circuit ID is left blank, LibreQoS will treat that device as its own Circuit. Circuit Name would be optional, but recommended. One good use for Circuit Name would be to put the customer's service location here.
