### ISSUE TITLE
Should we have to modify the queue size / Multi-Queue ?

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#69]
`ethtool -G eth2 rx 4096 tx 4096`

`ethtool -L eth2 combined 8`

[https://www.alibabacloud.com/help/en/elastic-compute-service/latest/configure-nic-multi-queue](https://www.alibabacloud.com/help/en/elastic-compute-service/latest/configure-nic-multi-queue)

[https://man7.org/linux/man-pages/man8/ethtool.8.html](https://man7.org/linux/man-pages/man8/ethtool.8.html)

[https://blog.cloudflare.com/how-to-achieve-low-latency/](https://blog.cloudflare.com/how-to-achieve-low-latency/)

[https://cromwell-intl.com/open-source/performance-tuning/ethernet.html](https://cromwell-intl.com/open-source/performance-tuning/ethernet.html)

**Comment by rchac** [comment]
There should be no need to modify the number of rx/tx queues. LibreQoS checks the number of rx/tx queues already, and makes sure to assign one CPU core per rx/tx queue. See [here](https://github.com/rchac/LibreQoS/blob/main/v1.1/LibreQoS.py#L98).

**Comment by marsalans** [comment]
Ahh good, i didn't notice the updated code in v1.1

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
