### ISSUE TITLE
v1.0 install documentation

### ISSUE THREAD

**Issue by osatjohnsenno** [rchac/LibreQoS#7]
Hello

Noticed the following things in the install notes for v1.0 / Ubuntu 21.10
https://github.com/rchac/LibreQoS/wiki/LibreQoS-v1.0-Installation-&-Usage-Guide---Physical-Server-and-Ubuntu-21.10

Under Install LibreQoS and dependencies:

`sudo apt-get install qemu-guest-agent`

Maybe not needed unless you run Proxmox :)

Under Install and compile XDP-CPUMAP-TC

`cd LibreQoS
git submodule update --init
cd /xdp-cpumap-tc/
git submodule update --init
cd /src/
make`

I had to go into the v1.0 subfolder to get the commands to run
`cd LibreQoS
cd v1.0
git submodule update --init
cd /xdp-cpumap-tc/
git submodule update --init
cd /src/
make`

Under How to run LibreQoS, Running as a service

`[Service]
WorkingDirectory=/home/$USER/LibreQoS
ExecStart=/usr/bin/python3 /home/$USER/LibreQoS/scheduled.py`

I had to add the v1.0 subfolder to the path to get the daemon to start
`[Service]
WorkingDirectory=/home/$USER/LibreQoS/v1.0
ExecStart=/usr/bin/python3 /home/$USER/LibreQoS/v1.0/scheduled.py`

**Comment by rchac** [comment]
Thank you very much for the corrections. I have made the changes to the v1.0 docs. If I missed anything please let me know.
