### ISSUE TITLE
Generate ParentNodes to handle entries without ParentNodes (CPU balance) (One site/AP and using XDP)

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#71]
I've got flat design in networks.json - only one site.
Flat design.

All of the commands:
 ```
./xdp-cpumap-tc/src/xdp_iphash_to_cpu_cmdline --add --ip 172.16.147.16 --cpu 0x0 --classid 0x1:0x1ae
key: 0x109310AC
```
All of the inserts got: **--cpu 0x0**

I suggest to assign RowNumber <-> CPU (as a sequence 1,2,3,4.... TOTAL_RXQUEUESCOUNT) and don't use Site<->CPU map.

<s>This could be controled by ispConfig.sh with variable:
**cpuassignment** with values sequence/site (default could be site for backward compatibility)</s>

Got another idea:
This could be controler by definition of site in `ShapeDevices.csv` - 
if site is not defined just use the sequence mentioned earlier here.

What do You think about it @rchac ?

**Comment by rchac** [comment]
That would break the HTB. HTBs on different CPU cores cannot "talk" to each other so they won't work in terms of balancing bandwidth. You can create additional top level parent nodes in Network.json (maybe dividing your primary site into 4, 6, 12 parts) so that you can evenly divide up the workload among CPU cores.

**Comment by interduo** [comment]
Correct me if I am wrong:
It doesn't matter for customers with no site because they don't got limit by class of the site

**Comment by rchac** [comment]
Ah ok I misunderstood. So you don't have any parent nodes defined in ShapedDevices.csv? If so, that is a good solution. My plan was to generate an equivalent number of "generated parent nodes" to CPU cores, then evenly distribute ShapedDevices.csv entries among those generated parent nodes. That would be helpful to many instances like yours.

**Comment by interduo** [comment]
If it will be done I could test this in real envirnoment at throughput ~6-10gbs and find some more bugs then :-)

**Comment by rchac** [comment]
This feature i can have ready in 1-3 days hopefully. I've wanted to add that for a while. I have a hectic work schedule starting shortly but when i have some downtime I can get this done. It's not too tricky to implement. That way you can test LibreQoS out and see how it does for you.

**Comment by interduo** [comment]
I will do temporary temporary workaround before this issue will be resolved.

I will change on CRM integration script some code and will be generating sequentialy siteA, siteB, siteC when generating ShapedDevices.csv.

**Comment by rchac** [comment]
Feature added https://github.com/rchac/LibreQoS/commit/30da53401bd904d3c729c85849755b35ff410491

**Comment by interduo** [comment]
@rchac could You add an example for flat design?

I tried:
cat network.json 

```
{
}
```

also tried: `echo -n > network.json` whitch generated me an error

So my suggestion is:
1. If network.json is empty don't shape by site and use autogenerated nodes,
2. default value of ShapeBySite is True - and it's marked as Depricated - even if it's commented out it is True ;-)

**Comment by rchac** [comment]
It seems to already support this. I tried a network.json with ```{}``` as the contents and it created the generated parent nodes and evenly distributed among CPU cores.

**Comment by interduo** [comment]
Yes thats why I crossed out this text. I had a syntax error inside.
