### ISSUE TITLE
Quest for a tagline for libreqos?

### ISSUE THREAD

**Issue by dtaht** [rchac/LibreQoS#72]
We (bufferbloat project), have tried to make "smart queue management" and "smart queues" and SQM a "term of art", and have succeeded to some extent.  https://www.bufferbloat.net/projects/cerowrt/wiki/Smart_Queue_Management/ . We didn't trademark it, but so far, everyone using the phrase more or less means what we described in this link, and the hope was that with more acceptance of this- "does your service have smart queues?" was more reachable to the market than, for example, than "do you have cake", or "fq_codel" or "rfc8290" - we've dithered with "working latency", "responsiveness", and other phrases like that. The discoverability of going from "my network is slow today" to "oh, I have bufferbloat", has always been a real problem.

A scar I have was that qualcomm adopted a dpi + fq_codel based solution back in 2013,  they created a name for it, although completely inaccurate, that I *loved*: Streamboost" - oh, what a great name! But hilariously, they convinced themselves it was all the dpi and qos and their backend service that was doing the job for em and after establishing that "brand", and shipping a couple (award winning) products, they skipped putting fq_codel entirely in one of their low-end products, which didn't work worth a damn, and after that the streamboost brand (and service!) sank without a trace.  

Anyway, that gets me up to libreqos in particular, needing a tag line. LibreQos - "something memorable" . I like that it's QoS, rather than SQM, because in the public mind  to what extent it exists, qos is what they think they want, even though it's sqm they need. I love "libre" because that's more associated with GPLv2 software than "open", and does imply "freedom with co-operation" to some people.  An ideal tagline is 6 words or less, that hit people on a pain (or joy!) point.

LibreQoS
    Building Better Bandwidth
    Fast, Flexible QoE
    Better Bandwidth
    Smarter Queue Management   

Very open to other ideas, and other descriptive bullet-y items, and feedback on the new website: https://libreqos.io/

**Comment by dtaht** [comment]
I have a very odd relationship with word coinage, I've read a lot of books on marketing - but mostly in self defense in finding ways to find the truth and filter out the BS. I'm highly influenced by doc searls' cluetrain manefesto, "the medium is the massage", and the like, and at the same time am painfully aware of the power of a well formed phrase - "open source", "bufferbloat", and so on. I've attempted to coin more than a few flops - "googlethrusting" for example. 

What I liked about blogs, was, for a brief time, they were an honest voice in the wilderness, and a two way street.

http://the-edge.blogspot.com/2003_06_08_the-edge_archive.html#200399808

**Comment by rchac** [comment]
I really like "Fast, Flexible QoE". QoE seems to be an increasingly recognized term in the industry, which is good. "Smarter Queue Management" is good too. Great suggestions.

**Comment by interduo** [comment]
this should go to discussion board
