### ISSUE TITLE
Revert to last working sharper csv

### ISSUE THREAD

**Issue by intelliserve** [rchac/LibreQoS#77]
Is it possible that if a new reading of the sharper files detects an error. It reverts to last working version and continues working until then next attempt.

**Comment by rchac** [comment]
Yes, that is currently how [v1.2](https://github.com/rchac/LibreQoS/tree/main/v1.2) works. If ShapedDevices.csv has any error, it will skip it and use the last working version which it backs up regularly. Prior versions do not have that feature though.

**Comment by intelliserve** [comment]
Thank you.
