### ISSUE TITLE
Reduce number of Points generated for influx

### ISSUE THREAD

**Issue by khandieyea** [rchac/LibreQoS#85]
I'm probably missing something here, but

In `graphBandwidth.py`, where the influx measurements are constructed https://github.com/rchac/LibreQoS/blob/45fa959810f8e8c230714123d709d7b754ec5f85/v1.1/graphBandwidth.py#L148-L151

Is there a particular reason for doing more or less the same measurement twice with differing fields?
Would the following yield the same queryable data in influx?
```python
Point('Bandwidth')
    .tag("Device", parentNode['parentNodeName'])
    .tag("ParentNode", parentNode['parentNodeName'])
    .tag("Type", "Parent Node")
    .field("Download", bitsDownload)
    .field("Upload", bitsUpload)
```

Thanks!

**Comment by rchac** [comment]
Thank you for catching this. I didn't realize at the time it was possible to use the same point object to store both fields. Fixed with https://github.com/rchac/LibreQoS/commit/1774579accbccc04b9b1477c7e026f4e3e3a4cd2

**Comment by khandieyea** [comment]
All good, glad my maim can stay in sync with upstream :)

**Comment by interduo** [comment]
@rchac is v1.2 affected by this issue?

**Comment by rchac** [comment]
@interduo v1.2 is no longer affected by this issue. https://github.com/rchac/LibreQoS/commit/6964aad28534a54987ac08d4ee66fcbb19d7cb0a
