### ISSUE TITLE
ShapedDevices.py validator should check if rate is lower than ceil

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#86]
Now it don't check that.

BTW What minimum HTB classes rate/ceil values are recommended for best performance?

**Comment by interduo** [comment]
```
root@rty-libreqos:~/LibreQoS2/v1.2# ./LibreQoS.py --validate
network.json passed validation
ShapedDevices.csv passed validation

root@rty-libreqos:~/LibreQoS2/v1.2# head -n2 ShapedDevices.csv 
#LMS customer queues file for LibreQoS - 2022-09-12 16:08
704, 3, 64, 100,,,"172.18.181.9",, 55, 55, 30, 4, KOMENTARZ

```

**Comment by rchac** [comment]
Fixed! Thanks for catching that, my apologies. https://github.com/rchac/LibreQoS/commit/938075b8fdc32560eda9d7887c92dbb4f3971387

**Comment by rchac** [comment]
Strange. I get
```
python3 LibreQoS.py --validate
network.json passed validation
/home/jackrabbit/LibreQoS/LibreQoS.py:194: UserWarning: Provided downloadMin '55' in ShapedDevices.csv at row 2 is greater than downloadMax
  warnings.warn("Provided downloadMin '" + downloadMin + "' in ShapedDevices.csv at row " + str(rowNum) + " is greater than downloadMax")
/home/jackrabbit/LibreQoS/LibreQoS.py:197: UserWarning: Provided uploadMin '55' in ShapedDevices.csv at row 2 is greater than uploadMax
  warnings.warn("Provided uploadMin '" + downloadMin + "' in ShapedDevices.csv at row " + str(rowNum) + " is greater than uploadMax")
ShapedDevices.csv failed validation
```

**Comment by interduo** [comment]
Now in `linux-tc.txt` there is:

```
class add dev ens16np0 parent 0xc:0x5ab classid 0x641 htb rate 1mbit ceil 164mbit prio 3
qdisc add dev ens16np0 parent 0xc:0x641 cake diffserv4
class add dev ens17np0 parent 0xc:0x5ab classid 0x641 htb rate 1mbit ceil 164mbit prio 3
qdisc add dev ens17np0 parent 0xc:0x641 cake diffserv4
```

I suggest also generating comments like:
```
class add dev ens16np0 parent 0xc:0x5ab classid 0x641 htb rate 1mbit ceil 164mbit prio 3 #CircuitID: 1234
qdisc add dev ens16np0 parent 0xc:0x641 cake diffserv4 #CircuitID: 1234
class add dev ens17np0 parent 0xc:0x5ab classid 0x641 htb rate 1mbit ceil 164mbit prio 3 #CircuitID: 1234
qdisc add dev ens17np0 parent 0xc:0x641 cake diffserv4 #CircuitID: 1234
```

This is important because we cannot connect lines in ShapedDevices.csv with generated `linux-tc.txt` and its not so easy to debug tc now.

**Comment by interduo** [comment]
> Strange. I get
> 
> ```
> python3 LibreQoS.py --validate
> network.json passed validation
> /home/jackrabbit/LibreQoS/LibreQoS.py:194: UserWarning: Provided downloadMin '55' in ShapedDevices.csv at row 2 is greater than downloadMax
>   warnings.warn("Provided downloadMin '" + downloadMin + "' in ShapedDevices.csv at row " + str(rowNum) + " is greater than downloadMax")
> /home/jackrabbit/LibreQoS/LibreQoS.py:197: UserWarning: Provided uploadMin '55' in ShapedDevices.csv at row 2 is greater than uploadMax
>   warnings.warn("Provided uploadMin '" + downloadMin + "' in ShapedDevices.csv at row " + str(rowNum) + " is greater than uploadMax")
> ShapedDevices.csv failed validation
> ```

Show me Your rule in ShapedDevices.csv

**Comment by rchac** [comment]
```
,,,,,,100.64.0.1,,55,55,30,4,
```
![image](https://user-images.githubusercontent.com/22501920/189701102-88bea568-0f1f-4231-a8a7-7833e3721bbb.png)

**Comment by interduo** [comment]
If I get Your line to my config - it throws an error.

Please try insert:
`704, 3, 64, 100,,,"172.18.181.9",,100,100,30,4, KOMENTARZ`

**Comment by rchac** [comment]
I think I figured it out. Your ShapedDevices.csv is missing a header field after the comment line.
You have:
```
#LMS customer queues file for LibreQoS - 2022-09-12 16:08
704, 3, 64, 100,,,"172.18.181.9",,100,100,30,4, KOMENTARZ
```
Usually it would be:
```
#LMS customer queues file for LibreQoS - 2022-09-12 16:08
Circuit ID,Circuit Name,Device ID,Device Name,Parent Node,MAC,IPv4,IPv6,Download Min,Upload Min,Download Max,Upload Max,Comment
704, 3, 64, 100,,,"172.18.181.9",,100,100,30,4, KOMENTARZ
```

**Comment by interduo** [comment]
ohhh I didn't know that it was required

**Comment by interduo** [comment]
What do You think about https://github.com/rchac/LibreQoS/issues/86#issuecomment-1243944440 ?

**Comment by rchac** [comment]
> @rchac what do You think about [#86 (comment)](https://github.com/rchac/LibreQoS/issues/86#issuecomment-1243944440) ?

Does this help? https://github.com/rchac/LibreQoS/commit/a924cc05dec604be530daefc1a1bc728282a9b32

**Comment by rchac** [comment]
```
python3 LibreQoS.py --verbose
```
I don't think linux tc supports comments in the batch files, so I have it print the comments using the verbose flag. I could be wrong though - if you find  linux tc supports comments in the batch files please let me know so we can add them there too.

**Comment by interduo** [comment]
If I tested correctly there is no problem in `--batch` to use `#comments` at the end of the line.

I did:
```
diff --git a/v1.2/LibreQoS.py b/v1.2/LibreQoS.py
index 4a66eb5..fee29e7 100644
--- a/v1.2/LibreQoS.py
+++ b/v1.2/LibreQoS.py
@@ -472,9 +472,9 @@ def refreshShapers():
                                                comment = "CircuitID: " + circuit['circuitID'] + " CircuitName: " + circuit['circuitName']
                                                command = 'class add dev ' + interfaceA + ' parent ' + elemClassID + ' classid ' + hex(minor) + ' htb rate '+ str(minDownload) + 'mbit ceil '+ str(maxDownload) + 'mbit prio 3'
                                                linuxTCcommands.append((command, comment))
-                                               command = 'qdisc add dev ' + interfaceA + ' parent ' + hex(major) + ':' + hex(minor) + ' ' + fqOrCAKE
+                                               command = 'qdisc add dev ' + interfaceA + ' parent ' + hex(major) + ':' + hex(minor) + ' ' + fqOrCAKE + ' #somecomment'
                                                linuxTCcommands.append((command, ''))
-                                               command = 'class add dev ' + interfaceB + ' parent ' + elemClassID + ' classid ' + hex(minor) + ' htb rate '+ str(minUpload) + 'mbit ceil '+ str(maxUpload) + 'mbit prio 3'
+                                               command = 'class add dev ' + interfaceB + ' parent ' + elemClassID + ' classid ' + hex(minor) + ' htb rate '+ str(minUpload) + 'mbit ceil '+ str(maxUpload) + 'mbit prio 3' + ' #somecomment'
                                                linuxTCcommands.append((command, ''))
                                                command = 'qdisc add dev ' + interfaceB + ' parent ' + hex(major) + ':' + hex(minor) + ' ' + fqOrCAKE
                                                linuxTCcommands.append((command, ''))

```

**Comment by rchac** [comment]
Great. Added https://github.com/rchac/LibreQoS/commit/fb74bad0b1e2bf03d44d62d6dac03be5d1743f74

**Comment by interduo** [comment]
Good work!!!! :)

**Comment by interduo** [comment]
Are You validating if the sum of customers rates are not over sites rate (in both autogenerate/network.json scenarios)?

**Comment by rchac** [comment]
Yes https://github.com/rchac/LibreQoS/blob/main/v1.2/LibreQoS.py#L467

**Comment by interduo** [comment]
I found small bug in validator/generator:
```
generatedPNDownloadMbps = 6000
generatedPNUploadMbps = 6000
```

Add customer (with a ceil over the generated parrent node)
`704, 3, 64, 100,,,"172.18.181.9",,50,50,7000,7000, KOMENTARZ`
