### ISSUE TITLE
WIKI INSTRUCTION: add performance/reability tip - production use

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#91]
CASE1: Reability tip tune - 1:
Please tune the OSPF timers:
- `hello interval`,
- `dead`,
in both OSPF neighbours.

CASE2: There is no step for finding InfluxDB DBToken and adding it to `ispConfig.py` from UI.

BTW today at 11:00 we implement LibreQoS for production use in our network. 

It took 21 days in total:
- research,
- testing implementation,
- issues/bugfixing,
- prod implementation
:)

**Comment by rchac** [comment]
Thanks. Added to wiki for v1.1 and v1.2

> BTW today at 11:00 we implement LibreQoS for production use in our network.

Nicely done! Thank you for contributing back upstream to the project so everyone can benefit. 🥳
