### ISSUE TITLE
Not so equal load on cpucores - sort by circuit ceil

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#99]
We have now the `ShapedDevices.csv` generated from the oldest to the newest client. This is okay mainly but the effect of this is that we got not so equal load on cpucores.

I strongly suggest sorting circuits by "ceil" before using `ShapedDevices.csv` (when no site is declared in network.json). This would give more equal cpu cores usage (of course: we assume that all customers utylise at the same percent theirs internet connections).

**Comment by rchac** [comment]
This makes sense. We can use [binpacking](https://pypi.org/project/binpacking/) to achieve this. I'll try to work on it.

**Comment by interduo** [comment]
Whitch metod is better in Your opinion
- sort by circuit ceil rate,
- sort by circuit network utilisation
?

**Comment by rchac** [comment]
Added! https://github.com/rchac/LibreQoS/commit/51299c357b34b7e955d1c957e92fc4d3af0c2ad6

**Comment by interduo** [comment]
I will test that deeply tommorow. Thanks!

**Comment by interduo** [comment]
I thought that the effects would more visible ;|

Probably we should use sorting based on past (from last full reload/based on tc counters)
